In [33]:
import os
import re
import time
import requests
import pandas as pd
import numpy as np
from tqdm import tqdm
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split

from itertools import permutations
import requests
import json

pd.set_option("display.max_rows", None, "display.max_columns", None)

# Headers to avoid rate limiting when scraping Sports Reference
SCRAPE_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

In [34]:
mens_path = os.path.abspath('../../data/mens_teams.csv')
mens_df = pd.read_csv(mens_path)
mens_df.head()

,School,"City, State",SR key,NCAA key,NCAA School,NCAA Name,background-color
0,Abilene Christian,"Abilene, Texas",abilene-christian,abilene-christian,Abilene Christian,Abilene Christian University,#582C83
1,Air Force,"USAF Academy, Colorado",air-force,air-force,Air Force,Air Force Academy,#0032A0
2,Akron,"Akron, Ohio",akron,akron,Akron,University of Akron,#0F192B
3,Alabama,"Tuscaloosa, Alabama",alabama,alabama,Alabama,University of Alabama,#9D2235
4,Alabama A&M,"Normal, Alabama",alabama-am,alabama-am,Alabama A&M,Alabama A&M University,#862633

In [35]:
womens_path = os.path.abspath('../../data/womens_teams.csv')
womens_df = pd.read_csv(womens_path)
womens_df.head()

,School,"City, State",SR key,NCAA key,NCAA School,NCAA Name,background-color
0,Abilene Christian,"Abilene, Texas",abilene-christian,abilene-christian,Abilene Christian,Abilene Christian University,#582C83
1,Air Force,"USAF Academy, Colorado",air-force,air-force,Air Force,Air Force Academy,#0032A0
2,Akron,"Akron, Ohio",akron,akron,Akron,University of Akron,#0F192B
3,Alabama,"Tuscaloosa, Alabama",alabama,alabama,Alabama,University of Alabama,#9D2235
4,Alabama A&M,"Normal, Alabama",alabama-am,alabama-am,Alabama A&M,Alabama A&M University,#862633

In [36]:
MENS_SR_SCHOOL_KEYS = [row.to_dict().get('SR key') for index, row in mens_df.iterrows()]
WOMENS_SR_SCHOOL_KEYS = [row.to_dict().get('SR key') for index, row in womens_df.iterrows()]

def get_gamelog_basic_url(school_key, season, isWomens = False):
    type = 'women' if isWomens else 'men'
    return f'https://www.sports-reference.com/cbb/schools/{school_key}/{type}/{season}-gamelogs.html'

def get_gamelog_advanced_url(school_key, season, isWomens = False):
    type = 'women' if isWomens else 'men'
    return f'https://www.sports-reference.com/cbb/schools/{school_key}/{type}/{season}-gamelogs-advanced.html'

def get_team_season_file_path(school_key, season, filename, isWomens = False):
    type = 'women' if isWomens else 'men'
    file_path = os.path.abspath(f'../../data/seasons/{season}/{school_key}/{type}/{filename}')

    dir = os.path.dirname(file_path)
    if not os.path.exists(dir):
        os.makedirs(dir)
    
    return file_path

## Download gamelogs HTML
Download the basic and advanced gamelog html for each team

In [37]:
def download_gamelog(school_key, season, isWomens = False):
    basic_url, advanced_url = get_gamelog_basic_url(school_key, season, isWomens), get_gamelog_advanced_url(school_key, season, isWomens)

    time.sleep(3) # Delay for 3 seconds
    basic_html = requests.get(basic_url, headers=SCRAPE_HEADERS).content
    time.sleep(3) # Delay for 3 seconds
    advanced_html = requests.get(advanced_url, headers=SCRAPE_HEADERS).content

    basic_file_path = get_team_season_file_path(school_key, season, f'{school_key}_basic.html', isWomens)
    advanced_file_path = get_team_season_file_path(school_key, season, f'{school_key}_advanced.html', isWomens)

    with open(basic_file_path, 'w') as file:
        file.write(basic_html.decode('utf-8'))
    with open(advanced_file_path, 'w') as file:
        file.write(advanced_html.decode('utf-8'))

def download_gamelogs_for_single_season(season, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season})'):
        download_gamelog(school_key, season, isWomens)

def download_gamelogs(seasons, isWomens = False):
    for season in seasons:
        download_gamelogs_for_single_season(season, isWomens)

In [6]:
# download_gamelogs([2025, 2026], isWomens = False)
# download_gamelogs([2025, 2026], isWomens = True)

100%|██████████| 491/491 [56:14<00:00,  6.87s/school (2025)]
100%|██████████| 491/491 [55:00<00:00,  6.72s/school (2026)]
100%|██████████| 370/370 [42:39<00:00,  6.92s/school (2025)]
100%|██████████| 370/370 [42:00<00:00,  6.81s/school (2026)]

## Change Opp name column to Opp key
The Opp name does not always match the school name we have saved in the team data, thus we will reparse the tables to instead use the SR keys

In [38]:
def get_opposing_school_keys(school_key, season, advanced = False, isWomens = False):
    opp_school_keys = []
    type = 'advanced' if advanced else 'basic'
    html_file_path = get_team_season_file_path(school_key, season, f'{school_key}_{type}.html', isWomens)

    with open(html_file_path, 'r') as file:
        soup = BeautifulSoup(file, 'html.parser')
        table = soup.find("table")
        rows = table.find_all('tr')
    
        for row in rows[2:]:
            try:
                link = row.find_all('td')[3].find('a')['href']
                key = re.search(r'/schools/([^/]+)/', link).group(1)

                if isWomens and '_w' in key:
                    key = key.replace('_w', '')
                opp_school_keys.append(key)
            except IndexError:
                # repeating header row
                continue
            except TypeError:
                #  opponent is missing
                opp_school_keys.append('')
            except AttributeError:
                #  opponent is missing
                opp_school_keys.append('')

    
    return opp_school_keys

## Basic gamelog CSV
Extract the basic gamelog to csv

In [39]:
def create_basic_gamelog(school_key, season, isWomens = False):
    file_path = get_team_season_file_path(school_key, season, f'{school_key}_basic.html', isWomens)

    team_df = pd.read_html(file_path)[0]

    # Flatten multi-level columns, prefixing opponent box score stats with 'def_'
    # These represent the team's DEFENSIVE performance (what opponents did against them)
    team_df.columns = [f'def_{col[1]}' if col[0] == 'Opponent' else col[1] for col in team_df.columns]

    # rename to location column
    team_df = team_df.rename(columns={'Unnamed: 3_level_1': 'Location'})

    # remove unneeded columns
    unneeded_columns = [column for column in team_df.columns if 'Unnamed' in column]
    team_df = team_df.drop(unneeded_columns, axis=1)

    # Drop repeating header rows
    team_df = team_df[team_df.Tm != 'Tm']
    team_df = team_df[team_df.FG != 'School']

    # rename repeating 'Opp' column
    index = team_df.columns.to_list().index('Opp')
    team_df.columns.values[index] = 'Opp name'

    # Opp names to Opp keys
    opp_school_keys = get_opposing_school_keys(school_key, season, False, isWomens)
    # Shape for both must match same rows
    assert team_df.shape[0] == len(opp_school_keys)

    team_df['Opp name'] = opp_school_keys
    team_df = team_df.rename(columns={'Opp name': 'Opp key'})

    # Remove averages row at end - remove rows where Rk is not a number
    team_df['Rk'] = pd.to_numeric(team_df['Rk'], errors='coerce')
    team_df = team_df.dropna(subset=['Rk'])

    # save file
    csv_file_path = get_team_season_file_path(school_key, season, f'{school_key}_basic.csv', isWomens)
    team_df.to_csv(csv_file_path, index=False)

def create_basic_gamelogs_for_single_season(season, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season} basic csv)'):
        try:
            create_basic_gamelog(school_key, season, isWomens)
        except ValueError:
            continue

def create_basic_gamelogs(seasons, isWomens = False):
    for season in seasons:
        create_basic_gamelogs_for_single_season(season, isWomens)

In [48]:
seasons = [2022, 2023, 2024, 2025, 2026]

# Step 1: Regenerate basic gamelogs (now keeps def_ opponent columns)
for isWomens in [False, True]:
    create_basic_gamelogs(seasons, isWomens=isWomens)

100%|██████████| 491/491 [02:48<00:00,  2.92school (2022 basic csv)/s]
100%|██████████| 491/491 [02:46<00:00,  2.94school (2023 basic csv)/s]
100%|██████████| 491/491 [02:49<00:00,  2.90school (2024 basic csv)/s]
100%|██████████| 491/491 [01:19<00:00,  6.18school (2025 basic csv)/s]
100%|██████████| 491/491 [01:15<00:00,  6.51school (2026 basic csv)/s]
100%|██████████| 370/370 [02:21<00:00,  2.61school (2022 basic csv)/s]
100%|██████████| 370/370 [02:24<00:00,  2.57school (2023 basic csv)/s]
100%|██████████| 370/370 [02:24<00:00,  2.56school (2024 basic csv)/s]
100%|██████████| 370/370 [01:10<00:00,  5.24school (2025 basic csv)/s]
100%|██████████| 370/370 [01:05<00:00,  5.61school (2026 basic csv)/s]

Quick visual verification:

In [51]:
school_key, season = 'connecticut', 2023
file_path = get_team_season_file_path(school_key, season, f'{school_key}_basic.csv', isWomens=False)
team_df = pd.read_csv(file_path)
team_df.head()

,Rk,Gtm,Date,Location,Opp key,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,def_FG,def_FGA,def_FG%,def_3P,def_3PA,def_3P%,def_2P,def_2PA,def_2P%,def_eFG%,def_FT,def_FTA,def_FT%,def_ORB,def_DRB,def_TRB,def_AST,def_STL,def_BLK,def_TOV,def_PF
0,1.0,1,2022-11-07,NaN,stonehill,REG (Non-Conf),W,85,54,NaN,29,63,0.460,5,24,0.208,24,39,0.615,0.500,22,31,0.710,15,25,40,16,11,8,15,20,16,45,0.356,5,17,0.294,11,28,0.393,0.411,17,22,0.773,4,16,20,9,10,2,23,21
1,2.0,2,2022-11-11,NaN,boston-university,REG (Non-Conf),W,86,57,NaN,31,55,0.564,10,21,0.476,21,34,0.618,0.655,14,26,0.538,11,29,40,17,4,3,14,18,18,53,0.340,2,12,0.167,16,41,0.390,0.358,19,24,0.792,7,21,28,6,8,1,13,21
2,3.0,3,2022-11-15,NaN,buffalo,REG (Non-Conf),W,84,64,NaN,28,63,0.444,6,23,0.261,22,40,0.550,0.492,22,28,0.786,12,25,37,17,11,6,15,13,25,58,0.431,5,17,0.294,20,41,0.488,0.474,9,13,0.692,4,22,26,9,8,2,18,23
3,4.0,4,2022-11-18,NaN,north-carolina-wilmington,REG (Non-Conf),W,86,50,NaN,28,52,0.538,10,22,0.455,18,30,0.600,0.635,20,23,0.870,5,28,33,20,3,5,10,19,17,55,0.309,3,15,0.200,14,40,0.350,0.336,13,20,0.650,11,16,27,5,6,3,12,20
4,5.0,5,2022-11-20,NaN,delaware-state,REG (Non-Conf),W,95,60,NaN,35,61,0.574,12,28,0.429,23,33,0.697,0.672,13,19,0.684,7,27,34,25,9,6,12,20,20,52,0.385,2,9,0.222,18,43,0.419,0.404,18,26,0.692,6,19,25,5,6,1,18,19

## Advanced gamelog CSV
Extract the advanced gamelog to csv

In [65]:
def create_advanced_gamelog(school_key, season, isWomens = False):
    file_path = get_team_season_file_path(school_key, season, f'{school_key}_advanced.html', isWomens)

    team_df = pd.read_html(file_path)[0]

    # Flatten multi-level columns, prefixing defensive four factors with 'def_'
    team_df.columns = [f'def_{col[1]}' if 'Defensive' in str(col[0]) else col[1] for col in team_df.columns]

    # Normalize: older seasons (pre-2025) use 'def_DRB%', newer use 'def_ORB%' — standardize to 'def_ORB%'
    team_df.rename(columns={'def_DRB%': 'def_ORB%'}, inplace=True)

    # rename to location column
    team_df = team_df.rename(columns={'Unnamed: 3_level_1': 'Location'})

    # remove unneeded columns
    unneeded_columns = [column for column in team_df.columns if 'Unnamed' in column]
    team_df = team_df.drop(unneeded_columns, axis=1)

    # Drop repeating header rows
    team_df = team_df[team_df.Tm != 'Tm']
    team_df = team_df[team_df['eFG%'] != 'Offensive Four Factors']

    # rename repeating 'Opp' column
    index = team_df.columns.to_list().index('Opp')
    team_df.columns.values[index] = 'Opp name'

    # Opp names to Opp keys
    opp_school_keys = get_opposing_school_keys(school_key, season, True, isWomens)
    # Shape for both must match same rows
    assert team_df.shape[0] == len(opp_school_keys)
    
    team_df['Opp name'] = opp_school_keys
    team_df = team_df.rename(columns={'Opp name': 'Opp key'})

    # Remove averages row at end - remove rows where Rk is not a number
    team_df['Rk'] = pd.to_numeric(team_df['Rk'], errors='coerce')
    team_df = team_df.dropna(subset=['Rk'])

    # save file
    csv_file_path = get_team_season_file_path(school_key, season, f'{school_key}_advanced.csv', isWomens)
    team_df.to_csv(csv_file_path, index=False)

def create_advanced_gamelogs_for_single_season(season, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season} advanced csv)'):
        try:
            create_advanced_gamelog(school_key, season, isWomens)
        except ValueError:
            continue

def create_advanced_gamelogs(seasons, isWomens = False):
    for season in seasons:
        create_advanced_gamelogs_for_single_season(season, isWomens)

In [69]:
# Step 2: Regenerate advanced gamelogs (now keeps def_ columns)
for isWomens in [False, True]:
    create_advanced_gamelogs(seasons, isWomens=isWomens)

100%|██████████| 491/491 [02:39<00:00,  3.09school (2022 advanced csv)/s]
100%|██████████| 491/491 [02:42<00:00,  3.03school (2023 advanced csv)/s]
100%|██████████| 491/491 [02:39<00:00,  3.08school (2024 advanced csv)/s]
100%|██████████| 491/491 [02:52<00:00,  2.85school (2025 advanced csv)/s]
100%|██████████| 491/491 [02:48<00:00,  2.92school (2026 advanced csv)/s]
100%|██████████| 370/370 [02:12<00:00,  2.80school (2022 advanced csv)/s]
100%|██████████| 370/370 [02:13<00:00,  2.76school (2023 advanced csv)/s]
100%|██████████| 370/370 [02:14<00:00,  2.75school (2024 advanced csv)/s]
100%|██████████| 370/370 [02:25<00:00,  2.55school (2025 advanced csv)/s]
100%|██████████| 370/370 [02:20<00:00,  2.63school (2026 advanced csv)/s]

Quick visual verification:

In [70]:
school_key, season = 'connecticut', 2023
file_path = get_team_season_file_path(school_key, season, f'{school_key}_advanced.csv', isWomens=False)
team_df = pd.read_csv(file_path)
team_df.head()

,Rk,Gtm,Date,Location,Opp key,Type,Rslt,Tm,Opp,OT,ORtg,DRtg,Pace,FTr,3PAr,TS%,TRB%,AST%,STL%,BLK%,eFG%,TOV%,ORB%,FT/FGA,def_eFG%,def_TOV%,def_ORB%,def_FT/FGA
0,1.0,1,2022-11-07,NaN,stonehill,REG (Non-Conf),W,85,54,NaN,111.7,71.0,76.1,0.492,0.381,0.547,66.7,55.2,14.5,28.6,0.500,16.2,48.4,0.349,0.411,29.3,51.6,0.378
1,2.0,2,2022-11-11,NaN,boston-university,REG (Non-Conf),W,86,57,NaN,122.2,81.0,70.4,0.473,0.382,0.638,58.8,54.8,5.7,7.3,0.655,17.2,34.4,0.255,0.358,16.8,65.6,0.358
2,3.0,3,2022-11-15,NaN,buffalo,REG (Non-Conf),W,84,64,NaN,106.7,81.3,78.7,0.444,0.365,0.550,58.7,60.7,14.0,14.6,0.492,16.4,35.3,0.349,0.474,21.9,64.7,0.155
3,4.0,4,2022-11-18,NaN,north-carolina-wilmington,REG (Non-Conf),W,86,50,NaN,128.9,74.9,66.7,0.442,0.423,0.683,55.0,71.4,4.5,12.5,0.635,13.7,23.8,0.385,0.336,15.7,76.2,0.236
4,5.0,5,2022-11-20,NaN,delaware-state,REG (Non-Conf),W,95,60,NaN,125.5,79.3,75.7,0.311,0.459,0.678,57.6,71.4,11.9,14.0,0.672,14.6,26.9,0.213,0.404,21.9,73.1,0.346

## Combine basic and advanced gamelog CSVs

In [41]:
def combine_basic_advanced_gamelog(school_key, season, isWomens = False):
    basic_file_path = get_team_season_file_path(school_key, season, f'{school_key}_basic.csv', isWomens)
    advanced_file_path = get_team_season_file_path(school_key, season, f'{school_key}_advanced.csv', isWomens)

    basic_team_df, advanced_team_df = pd.read_csv(basic_file_path), pd.read_csv(advanced_file_path)

    # Drop def_eFG% from advanced (already present in basic opponent stats) to avoid merge conflicts
    advanced_team_df = advanced_team_df.drop(columns=['def_eFG%'], errors='ignore')

    merged_team_df = pd.merge(basic_team_df, advanced_team_df, on=['Rk', 'Gtm', 'Date', 'Location', 'Opp key', 'Type', 'Rslt', 'Tm', 'Opp', 'OT', 'eFG%'])

    # fill NaN location values to 'H' to represent Home
    merged_team_df['Location'] = merged_team_df['Location'].fillna('H')

    # if OT column is NaN, set to 0, otherwise set to 1
    merged_team_df['OT'] = np.where(merged_team_df['OT'].notna(), 1, 0)
    
    csv_file_path = get_team_season_file_path(school_key, season, f'{school_key}_merged.csv', isWomens)
    merged_team_df.to_csv(csv_file_path, index=False)

def combine_basic_advanced_gamelogs_for_single_season(season, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season} merged csv)'):
        try:
            combine_basic_advanced_gamelog(school_key, season, isWomens)
        except FileNotFoundError:
            continue

def combine_basic_advanced_gamelogs(seasons, isWomens = False):
    for season in seasons:
        combine_basic_advanced_gamelogs_for_single_season(season, isWomens)

In [71]:
# Step 3: Regenerate merged gamelogs (drops dup def_eFG%)
for isWomens in [False, True]:
    combine_basic_advanced_gamelogs(seasons, isWomens=isWomens)

100%|██████████| 491/491 [00:22<00:00, 21.42school (2022 merged csv)/s]
100%|██████████| 491/491 [00:24<00:00, 20.30school (2023 merged csv)/s]
100%|██████████| 491/491 [00:23<00:00, 21.10school (2024 merged csv)/s]
100%|██████████| 491/491 [00:21<00:00, 22.41school (2025 merged csv)/s]
100%|██████████| 491/491 [00:21<00:00, 22.87school (2026 merged csv)/s]
100%|██████████| 370/370 [00:21<00:00, 17.57school (2022 merged csv)/s]
100%|██████████| 370/370 [00:21<00:00, 17.54school (2023 merged csv)/s]
100%|██████████| 370/370 [00:20<00:00, 17.92school (2024 merged csv)/s]
100%|██████████| 370/370 [00:21<00:00, 17.54school (2025 merged csv)/s]
100%|██████████| 370/370 [00:21<00:00, 17.33school (2026 merged csv)/s]

Quick visual verification:

In [72]:
school_key, season = 'connecticut', 2023
file_path = get_team_season_file_path(school_key, season, f'{school_key}_merged.csv', isWomens=False)
team_df = pd.read_csv(file_path)
team_df.head()

,Rk,Gtm,Date,Location,Opp key,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,def_FG,def_FGA,def_FG%,def_3P,def_3PA,def_3P%,def_2P,def_2PA,def_2P%,def_eFG%,def_FT,def_FTA,def_FT%,def_ORB,def_DRB,def_TRB,def_AST,def_STL,def_BLK,def_TOV,def_PF,ORtg,DRtg,Pace,FTr,3PAr,TS%,TRB%,AST%,STL%,BLK%,TOV%,ORB%,FT/FGA,def_TOV%,def_ORB%,def_FT/FGA
0,1.0,1,2022-11-07,H,stonehill,REG (Non-Conf),W,85,54,0,29,63,0.460,5,24,0.208,24,39,0.615,0.500,22,31,0.710,15,25,40,16,11,8,15,20,16,45,0.356,5,17,0.294,11,28,0.393,0.411,17,22,0.773,4,16,20,9,10,2,23,21,111.7,71.0,76.1,0.492,0.381,0.547,66.7,55.2,14.5,28.6,16.2,48.4,0.349,29.3,51.6,0.378
1,2.0,2,2022-11-11,H,boston-university,REG (Non-Conf),W,86,57,0,31,55,0.564,10,21,0.476,21,34,0.618,0.655,14,26,0.538,11,29,40,17,4,3,14,18,18,53,0.340,2,12,0.167,16,41,0.390,0.358,19,24,0.792,7,21,28,6,8,1,13,21,122.2,81.0,70.4,0.473,0.382,0.638,58.8,54.8,5.7,7.3,17.2,34.4,0.255,16.8,65.6,0.358
2,3.0,3,2022-11-15,H,buffalo,REG (Non-Conf),W,84,64,0,28,63,0.444,6,23,0.261,22,40,0.550,0.492,22,28,0.786,12,25,37,17,11,6,15,13,25,58,0.431,5,17,0.294,20,41,0.488,0.474,9,13,0.692,4,22,26,9,8,2,18,23,106.7,81.3,78.7,0.444,0.365,0.550,58.7,60.7,14.0,14.6,16.4,35.3,0.349,21.9,64.7,0.155
3,4.0,4,2022-11-18,H,north-carolina-wilmington,REG (Non-Conf),W,86,50,0,28,52,0.538,10,22,0.455,18,30,0.600,0.635,20,23,0.870,5,28,33,20,3,5,10,19,17,55,0.309,3,15,0.200,14,40,0.350,0.336,13,20,0.650,11,16,27,5,6,3,12,20,128.9,74.9,66.7,0.442,0.423,0.683,55.0,71.4,4.5,12.5,13.7,23.8,0.385,15.7,76.2,0.236
4,5.0,5,2022-11-20,H,delaware-state,REG (Non-Conf),W,95,60,0,35,61,0.574,12,28,0.429,23,33,0.697,0.672,13,19,0.684,7,27,34,25,9,6,12,20,20,52,0.385,2,9,0.222,18,43,0.419,0.404,18,26,0.692,6,19,25,5,6,1,18,19,125.5,79.3,75.7,0.311,0.459,0.678,57.6,71.4,11.9,14.0,14.6,26.9,0.213,21.9,73.1,0.346

## Generating Moving Averages
Next we will generate a csv adding the moving averages for each statistic

In [66]:
LATEST = 'LATEST'
META_LABELS = ['Rk', 'Gtm', 'Date', 'Location', 'Opp key', 'Type', 'Rslt', 'Tm', 'Opp']

# Offensive stats (from basic Team section + advanced Offensive Four Factors + Advanced)
OFFENSIVE_STAT_LABELS = [
    'OT', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
    'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
    'ORtg', 'DRtg', 'Pace', 'FTr', '3PAr', 'TS%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'ORB%', 'FT/FGA'
]

# Defensive stats — opponent box score (from basic Opponent section) + Defensive Four Factors
# These capture what opponents did AGAINST this team (i.e., this team's defensive profile)
# Note: Sports Reference renamed 'DRB%' to 'ORB%' in the Defensive Four Factors around 2025;
#       we normalize to 'def_ORB%' in create_advanced_gamelog for consistency across all seasons.
DEFENSIVE_STAT_LABELS = [
    'def_FG', 'def_FGA', 'def_FG%', 'def_3P', 'def_3PA', 'def_3P%',
    'def_2P', 'def_2PA', 'def_2P%', 'def_eFG%', 'def_FT', 'def_FTA', 'def_FT%',
    'def_ORB', 'def_DRB', 'def_TRB', 'def_AST', 'def_STL', 'def_BLK', 'def_TOV', 'def_PF',
    'def_TOV%', 'def_ORB%', 'def_FT/FGA'
]

STAT_LABELS = OFFENSIVE_STAT_LABELS + DEFENSIVE_STAT_LABELS
print(f'Total stat labels: {len(STAT_LABELS)} ({len(OFFENSIVE_STAT_LABELS)} offensive + {len(DEFENSIVE_STAT_LABELS)} defensive)')

Total stat labels: 59 (35 offensive + 24 defensive)

In [43]:
def generate_moving_averages_for_school(school_key, season, keep_latest = False, span = 5, isWomens = False):
    file_path = get_team_season_file_path(school_key, season, f'{school_key}_merged.csv', isWomens)
    team_df = pd.read_csv(file_path)

    # Drop any rows with NULL values
    team_df.dropna(inplace=True)

    if keep_latest:
        # This logic makes it so we keep the latest statistics for an upcoming game
        copyLast = pd.DataFrame(team_df.tail(1).values, columns=team_df.columns)
        team_df = pd.concat([team_df, copyLast], ignore_index=True)
        team_df.loc[team_df.index[-1], 'Date'] = LATEST
        team_df.loc[team_df.index[-1], 'Opp key'] = LATEST

    # Compute all moving averages in one batch to avoid DataFrame fragmentation
    ma_frames = []
    for column in team_df.columns:
        if column in META_LABELS:
            continue

        vals = team_df.loc[:, column]
        sma = vals.rolling(window=span).mean().shift(1)
        cma = vals.expanding(min_periods=span).mean().shift(1)
        ema = vals.ewm(span=span, adjust=False).mean().shift(1)

        ma_frames.append(pd.DataFrame({
            f"{column}_SMA": sma,
            f"{column}_CMA": cma,
            f"{column}_EMA": ema
        }))

    team_df = pd.concat([team_df] + ma_frames, axis=1)

    # Drop any rows with NULL values (rows with no MA)
    team_df.dropna(inplace=True)
    
    ma_file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}ma.csv', isWomens)
    team_df.to_csv(ma_file_path, index=False)

def generate_moving_averages_for_single_season(season, keep_latest = False, span = 5, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season} ma csv)'):
        try:
            generate_moving_averages_for_school(school_key, season, keep_latest, span, isWomens)
        except FileNotFoundError:
            continue

def generate_moving_averages(seasons, keep_latest = False, span = 5, isWomens = False):
    for season in seasons:
        generate_moving_averages_for_single_season(season, keep_latest, span, isWomens)

In [73]:
# Step 4: Regenerate moving averages
for span in [3, 5, 7]:
    for isWomens in [False, True]:
        generate_moving_averages(seasons, keep_latest=False, span=span, isWomens=isWomens)

100%|██████████| 491/491 [00:27<00:00, 17.94school (2022 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.43school (2023 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.34school (2024 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.34school (2025 ma csv)/s]
100%|██████████| 491/491 [00:25<00:00, 19.27school (2026 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.63school (2022 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.45school (2023 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.55school (2024 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.44school (2025 ma csv)/s]
100%|██████████| 370/370 [00:24<00:00, 15.05school (2026 ma csv)/s]
100%|██████████| 491/491 [00:25<00:00, 19.23school (2022 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.48school (2023 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.49school (2024 ma csv)/s]
100%|██████████| 491/491 [00:27<00:00, 17.97school (2025 ma csv)/s]
100%|██████████| 491/491 [00:25<00:00, 19.08school (2026 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.68school (2022 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.71school (2023 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.45school (2024 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.62school (2025 ma csv)/s]
100%|██████████| 370/370 [00:24<00:00, 14.93school (2026 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.74school (2022 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.27school (2023 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.40school (2024 ma csv)/s]
100%|██████████| 491/491 [00:26<00:00, 18.44school (2025 ma csv)/s]
100%|██████████| 491/491 [00:25<00:00, 19.44school (2026 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.51school (2022 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.55school (2023 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.37school (2024 ma csv)/s]
100%|██████████| 370/370 [00:25<00:00, 14.62school (2025 ma csv)/s]
100%|██████████| 370/370 [00:24<00:00, 14.86school (2026 ma csv)/s]

Quick visual verification:

In [75]:
school_key, season, span = 'connecticut', 2023, 5
file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}ma.csv', isWomens=False)
team_df = pd.read_csv(file_path)
team_df.head()

,Rk,Gtm,Date,Location,Opp key,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,def_FG,def_FGA,def_FG%,def_3P,def_3PA,def_3P%,def_2P,def_2PA,def_2P%,def_eFG%,def_FT,def_FTA,def_FT%,def_ORB,def_DRB,def_TRB,def_AST,def_STL,def_BLK,def_TOV,def_PF,ORtg,DRtg,Pace,FTr,3PAr,TS%,TRB%,AST%,STL%,BLK%,TOV%,ORB%,FT/FGA,def_TOV%,def_ORB%,def_FT/FGA,OT_SMA,OT_CMA,OT_EMA,FG_SMA,FG_CMA,FG_EMA,FGA_SMA,FGA_CMA,FGA_EMA,FG%_SMA,FG%_CMA,FG%_EMA,3P_SMA,3P_CMA,3P_EMA,3PA_SMA,3PA_CMA,3PA_EMA,3P%_SMA,3P%_CMA,3P%_EMA,2P_SMA,2P_CMA,2P_EMA,2PA_SMA,2PA_CMA,2PA_EMA,2P%_SMA,2P%_CMA,2P%_EMA,eFG%_SMA,eFG%_CMA,eFG%_EMA,FT_SMA,FT_CMA,FT_EMA,FTA_SMA,FTA_CMA,FTA_EMA,FT%_SMA,FT%_CMA,FT%_EMA,ORB_SMA,ORB_CMA,ORB_EMA,DRB_SMA,DRB_CMA,DRB_EMA,TRB_SMA,TRB_CMA,TRB_EMA,AST_SMA,AST_CMA,AST_EMA,STL_SMA,STL_CMA,STL_EMA,BLK_SMA,BLK_CMA,BLK_EMA,TOV_SMA,TOV_CMA,TOV_EMA,PF_SMA,PF_CMA,PF_EMA,def_FG_SMA,def_FG_CMA,def_FG_EMA,def_FGA_SMA,def_FGA_CMA,def_FGA_EMA,def_FG%_SMA,def_FG%_CMA,def_FG%_EMA,def_3P_SMA,def_3P_CMA,def_3P_EMA,def_3PA_SMA,def_3PA_CMA,def_3PA_EMA,def_3P%_SMA,def_3P%_CMA,def_3P%_EMA,def_2P_SMA,def_2P_CMA,def_2P_EMA,def_2PA_SMA,def_2PA_CMA,def_2PA_EMA,def_2P%_SMA,def_2P%_CMA,def_2P%_EMA,def_eFG%_SMA,def_eFG%_CMA,def_eFG%_EMA,def_FT_SMA,def_FT_CMA,def_FT_EMA,def_FTA_SMA,def_FTA_CMA,def_FTA_EMA,def_FT%_SMA,def_FT%_CMA,def_FT%_EMA,def_ORB_SMA,def_ORB_CMA,def_ORB_EMA,def_DRB_SMA,def_DRB_CMA,def_DRB_EMA,def_TRB_SMA,def_TRB_CMA,def_TRB_EMA,def_AST_SMA,def_AST_CMA,def_AST_EMA,def_STL_SMA,def_STL_CMA,def_STL_EMA,def_BLK_SMA,def_BLK_CMA,def_BLK_EMA,def_TOV_SMA,def_TOV_CMA,def_TOV_EMA,def_PF_SMA,def_PF_CMA,def_PF_EMA,ORtg_SMA,ORtg_CMA,ORtg_EMA,DRtg_SMA,DRtg_CMA,DRtg_EMA,Pace_SMA,Pace_CMA,Pace_EMA,FTr_SMA,FTr_CMA,FTr_EMA,3PAr_SMA,3PAr_CMA,3PAr_EMA,TS%_SMA,TS%_CMA,TS%_EMA,TRB%_SMA,TRB%_CMA,TRB%_EMA,AST%_SMA,AST%_CMA,AST%_EMA,STL%_SMA,STL%_CMA,STL%_EMA,BLK%_SMA,BLK%_CMA,BLK%_EMA,TOV%_SMA,TOV%_CMA,TOV%_EMA,ORB%_SMA,ORB%_CMA,ORB%_EMA,FT/FGA_SMA,FT/FGA_CMA,FT/FGA_EMA,def_TOV%_SMA,def_TOV%_CMA,def_TOV%_EMA,def_ORB%_SMA,def_ORB%_CMA,def_ORB%_EMA,def_FT/FGA_SMA,def_FT/FGA_CMA,def_FT/FGA_EMA
0,6.0,6,2022-11-24,N,oregon,REG (Non-Conf),W,83,59,0,30,63,0.476,17,37,0.459,13,26,0.500,0.611,6,11,0.545,11,24,35,22,9,7,11,25,20,47,0.426,5,15,0.333,15,32,0.469,0.479,14,25,0.560,3,23,26,11,5,4,16,16,118.5,84.2,70.1,0.175,0.587,0.608,57.4,73.3,12.8,21.9,13.9,32.4,0.095,21.4,67.6,0.298,0.0,0.0,0.0,30.2,30.200000,30.827160,58.8,58.800000,59.098765,0.5160,0.516000,0.523235,8.6,8.600000,9.086420,23.6,23.600000,24.444444,0.3658,0.365800,0.370877,21.6,21.600000,21.740741,35.2,35.200000,34.654321,0.6160,0.616000,0.629667,0.5908,0.590800,0.601457,18.2,18.200000,17.765432,25.4,25.400000,24.283951,0.7176,0.717600,0.731160,10.0,10.000000,9.271605,26.8,26.800000,26.728395,36.8,36.800000,36.000000,19.0,19.000000,20.135802,7.6,7.600000,7.864198,5.6,5.600000,5.876543,13.2,13.200000,12.790123,18.0,18.000000,18.543210,19.2,19.200000,19.086420,52.6,52.600000,52.271605,0.3642,0.364200,0.364753,3.4,3.400000,3.259259,14.0,14.000000,13.395062,0.2354,0.235400,0.236568,15.8,15.800000,15.827160,38.6,38.600000,38.876543,0.4080,0.408000,0.405889,0.3966,0.396600,0.396099,15.2,15.200000,15.456790,21.0,21.000000,21.753086,0.7198,0.719800,0.708543,6.4,6.400000,6.518519,18.8,18.800000,18.382716,25.2,25.200000,24.901235,6.8,6.800000,6.481481,7.6,7.600000,7.283951,1.8,1.800000,1.790123,16.8,16.800000,17.160494,20.8,20.800000,20.407407,119.00,119.000000,120.418519,77.50,77.500000,77.146914,73.52,73.520000,73.700000,0.4324,0.432400,0.411568,0.4020,0.402000,0.414062,0.6192,0.619200,0.630321,59.36,59.360000,59.101235,62.70,62.700000,64.975309,10.12,10.120000,10.467901,15.40,15.400000,15.977778,15.62,15.620000,15.239506,33.76,33.760000,32.443210,0.3102,0.310200,0.302383,21.12,21.120000,21.480247,66.24,66.240000,67.556790,0.2946,0.294600,0.300765
1,7.0,7,2022-11-25,N,alabama,REG (Non-Conf),W,82,67,0,26,60,0.433,9,24,0.375,17,36,0.472,0.508,21,24,0.875,8,22,30,18,8,7,11,23,21,50,0.420,6,16,0.375,15,34,0.441,0.480,19,25,0.760,7,25,32,10,4,6,19,23,110.6,90.4,74.1,0.400,0.400,0.574,48.4,69.2,10.8,20.6,13.3,24.2,0.350,23.5,75.8,0.380,0.0,0.0,0.0,30.4,30.166667,30.551440,58.8,59.500000,60.399177,0.5192,0.509333,0.507490,11.0,10.000000,11.724280,26.2,25.833333,28.629630,0.4160,0.381333,0.400251,19.4,20.166667,18.827160,32.6,33.666667,31.769547,0.5930,0.596667,0.586444,0.6130,0.594167,0.604638,15.0,16.166667,13.843621,21.4,23.000000,19.855967,0.6846,0.688833,0.669107,9.2,10.166667,9.847737,26.6,26.333333,25.818930,35.8,36.500000,35.666667,20.2,19.500000,20.757202,7.2,7.833333,8.242798,5.4,5.833333,6.251029,12.4,12.833333,12.193416,19.0,19.166667,20.695473,20.0,19.333333,19.390947,53.0,51.666667,50.514403,0.3782,0.374500,0.385169,3.4,3.666667,3.839506,13.6,14.166667,13.930041,0.2432,0.251667,0.268712,16.6,15.666667,15.551440,39.4,37.500000,36.584362,0.4232,0.418167,0.426926,0.4102,0.410333,0.423733,14.6,15.000000,14.971193,21.6,21.666667,22.835391,0.6772,0.693167,0.659029,6.2,5.833333,5.345679,20.2,19.500000,19.921811,26.4,25.333333,25.267490,7.2,7.500000,7.987654,6.6,7.166667,6.522634,2.2,2.166667,2.526749,15.4,16.666667,16.773663,19.8,20.000000,18.938272,120.36,118.916667,119.779012,80.14,78.616667,79.497942,72.32,72.950000,72.500000,0.3690,0.389500,0.332712,0.4432,0.432833,0.471708,0.6314,0.617333,0.622881,57.50,59.033333,58.534156,66.32,64.466667,67.750206,9.78,10.566667,11.245267,14.06,16.483333,17.951852,15.16,15.333333,14.793004,30.56,33.533333,32.428807,0.2594,0.274333,0.233255,19.54,21.166667,21.453498,69.44,66.466667,67.571193,0.2786,0.295167,0.299844
2,8.0,8,2022-11-27,N,iowa-state,REG (Non-Conf),W,71,53,0,22,53,0.415,7,26,0.269,15,27,0.556,0.481,20,25,0.800,18,27,45,16,5,2,17,15,22,54,0.407,3,13,0.231,19,41,0.463,0.435,6,10,0.600,7,12,19,9,13,0,10,21,113.0,84.4,62.8,0.472,0.491,0.547,70.3,72.7,8.0,4.9,20.8,60.0,0.377,14.5,40.0,0.111,0.0,0.0,0.0,29.4,29.571429,29.034294,59.8,59.571429,60.266118,0.4930,0.498429,0.482660,10.8,9.857143,10.816187,26.8,25.571429,27.086420,0.3958,0.380429,0.391834,18.6,19.714286,18.218107,33.0,34.000000,33.179698,0.5638,0.578857,0.548296,0.5836,0.581857,0.572425,16.4,16.857143,16.229081,21.0,23.142857,21.237311,0.7520,0.715429,0.737738,8.6,9.857143,9.231824,25.2,25.714286,24.545953,33.8,35.571429,33.777778,20.4,19.285714,19.838134,8.0,7.857143,8.161866,6.2,6.000000,6.500686,11.8,12.571429,11.795610,20.0,19.714286,21.463649,20.6,19.571429,19.927298,52.4,51.428571,50.342936,0.3942,0.381000,0.396779,4.2,4.000000,4.559671,14.4,14.428571,14.620027,0.2848,0.269286,0.304141,16.4,15.571429,15.367627,38.0,37.000000,35.722908,0.4334,0.421429,0.431617,0.4346,0.420286,0.442488,14.6,15.571429,16.314129,21.8,22.142857,23.556927,0.6708,0.702714,0.692686,6.2,6.000000,5.897119,21.0,20.285714,21.614540,27.2,26.285714,27.511660,8.0,7.857143,8.658436,5.8,6.714286,5.681756,3.2,2.714286,3.684499,16.6,17.000000,17.515775,20.2,20.428571,20.292181,118.04,117.728571,116.719342,82.02,80.300000,83.131962,73.06,73.114286,73.033333,0.3544,0.391000,0.355141,0.4468,0.428143,0.447805,0.6186,0.611143,0.606587,55.42,57.514286,55.156104,69.20,65.142857,68.233471,10.80,10.600000,11.096845,16.72,17.071429,18.834568,14.38,15.042857,14.295336,28.52,32.200000,29.685871,0.2784,0.285143,0.272170,20.88,21.500000,22.135665,71.48,67.800000,70.314129,0.2830,0.307286,0.326562
3,9.0,9,2022-12-01,H,oklahoma-state,REG (Non-Conf),W,74,64,0,21,56,0.375,8,23,0.348,13,33,0.394,0.446,24,33,0.727,10,18,28,11,8,3,6,16,22,56,0.393,4,11,0.364,18,45,0.400,0.429,16,19,0.842,11,23,34,5,4,3,16,25,107.5,93.0,68.9,0.589,0.411,0.516,45.2,52.4,11.6,6.7,7.7,30.3,0.429,19.7,69.7,0.286,0.0,0.0,0.0,28.2,28.625000,26.689529,57.8,58.750000,57.844079,0.4872,0.488000,0.460107,11.0,9.500000,9.544124,27.4,25.625000,26.724280,0.3974,0.366500,0.350889,17.2,19.125000,17.145405,30.4,33.125000,31.119799,0.5650,0.576000,0.550864,0.5814,0.569250,0.541950,16.0,17.250000,17.486054,20.4,23.375000,22.491541,0.7548,0.726000,0.758492,9.8,10.875000,12.154550,25.6,25.875000,25.363969,35.4,36.750000,37.518519,20.2,18.875000,18.558756,6.8,7.500000,7.107910,5.4,5.500000,5.000457,12.2,13.125000,13.530407,20.4,19.125000,19.309099,20.0,19.875000,20.618198,51.6,51.750000,51.561957,0.3894,0.384250,0.400186,3.8,3.875000,4.039781,13.6,14.250000,14.080018,0.2722,0.264500,0.279761,16.2,16.000000,16.578418,38.0,37.500000,37.481939,0.4284,0.426625,0.442078,0.4268,0.422125,0.439992,14.0,14.375000,12.876086,21.2,20.625000,19.037952,0.6524,0.689875,0.661791,6.8,6.125000,6.264746,19.0,19.250000,18.409694,25.8,25.375000,24.674440,8.0,8.000000,8.772291,6.8,7.500000,8.121171,2.8,2.375000,2.456333,15.0,16.125000,15.010517,19.8,20.500000,20.528121,119.30,117.137500,115.479561,82.64,80.812500,83.554641,69.88,71.825000,69.622222,0.3600,0.401125,0.394094,0.4720,0.436000,0.462203,0.6180,0.603125,0.586725,57.74,59.112500,60.204070,71.60,66.087500,69.722314,9.60,10.275000,10.064563,14.78,15.550000,14.189712,15.26,15.762500,16.463557,33.46,35.675000,39.790581,0.2840,0.296625,0.307113,19.40,20.625000,19.590444,66.54,64.325000,60.209419,0.2742,0.282750,0.254708
4,10.0,10,2022-12-07,@,florida,REG (Non-Conf),W,75,54,0,30,58,0.517,7,19,0.368,23,39,0.590,0.578,8,9,0.889,8,31,39,16,9,7,15,19,16,53,0.302,4,15,0.267,12,38,0.316,0.340,18,28,0.643,6,19,25,6,8,6,12,14,106.0,76.3,70.8,0.155,0.328,0.602,60.9,53.3,12.7,18.4,19.4,29.6,0.138,15.3,70.4,0.340,0.0,0.0,0.0,26.8,27.777778,24.793019,58.6,58.444444,57.229386,0.4546,0.475444,0.431738,10.6,9.333333,9.029416,27.6,25.333333,25.482853,0.3760,0.364444,0.349926,16.2,18.444444,15.763603,31.0,33.111111,31.746533,0.5238,0.555778,0.498576,0.5436,0.555556,0.509967,16.8,18.000000,19.657369,22.4,24.444444,25.994361,0.7262,0.726111,0.747995,10.8,10.777778,11.436366,23.6,25.000000,22.909313,34.4,35.777778,34.345679,18.4,18.000000,16.039171,7.8,7.555556,7.405274,5.0,5.222222,4.333638,11.4,12.333333,11.020271,19.8,18.777778,18.206066,21.0,20.111111,21.078799,51.8,52.222222,53.041305,0.4062,0.385222,0.397791,4.0,3.888889,4.026520,12.8,13.888889,13.053346,0.3050,0.275556,0.307841,17.0,16.222222,17.052279,39.0,38.333333,39.987959,0.4384,0.423667,0.428052,0.4454,0.422889,0.436328,14.6,14.555556,13.917391,21.0,20.444444,19.025301,0.6908,0.706778,0.721860,6.8,6.666667,7.843164,20.4,19.666667,19.939796,27.2,26.333333,27.782960,8.0,7.666667,7.514861,6.4,7.111111,6.747447,2.8,2.444444,2.637555,15.8,16.111111,15.340344,20.8,21.000000,22.018747,115.02,116.066667,112.819707,86.26,82.166667,86.703094,70.32,71.500000,69.381481,0.3894,0.422000,0.459063,0.4696,0.433222,0.445136,0.5846,0.593444,0.563150,55.78,57.566667,55.202713,67.80,64.566667,63.948209,11.02,10.422222,10.576376,13.62,14.566667,11.693141,14.06,14.866667,13.542372,34.76,35.077778,36.627054,0.2928,0.311333,0.347742,20.20,20.522222,19.626962,65.24,64.922222,63.372946,0.2842,0.283111,0.265139

## Merge opponent data

In [67]:
all_stat_cols = [item for col in STAT_LABELS for item in [col, f'{col}_SMA', f'{col}_CMA', f'{col}_EMA']]
opposing_stat_cols = [item for col in STAT_LABELS for item in [f'opp_{col}', f'opp_{col}_SMA', f'opp_{col}_CMA', f'opp_{col}_EMA']]
rename_opposing_cols = {item: f'opp_{item}' for stat in STAT_LABELS for item in [f'{stat}', f'{stat}_SMA', f'{stat}_CMA', f'{stat}_EMA']}

def merge_opponent_data_for_school(school_key, season, span = 5, isWomens = False):
    file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}ma.csv', isWomens)
    team_df = pd.read_csv(file_path)

    if team_df.shape[0] < 1:
        return

    home_df, away_df = pd.DataFrame(), pd.DataFrame()
    for index, row in team_df.iterrows():
        try:
            game_obj = row.to_dict()
            opponent_key = game_obj.get('Opp key')

            opponent_file_path = get_team_season_file_path(opponent_key, season, f'{opponent_key}_{span}ma.csv', isWomens)
            opponent_df = pd.read_csv(opponent_file_path)

            opponent_df = opponent_df.loc[(opponent_df['Opp key'] == school_key) & (opponent_df['Date'] == game_obj.get('Date'))]
            current_df = team_df[(team_df['Opp key'] == game_obj.get('Opp key')) & (team_df['Date'] == game_obj.get('Date'))]

            if game_obj.get('Location') == '@':
                home_df, away_df = pd.concat([home_df, opponent_df]), pd.concat([away_df, current_df])
            else:
                home_df, away_df = pd.concat([home_df, current_df]), pd.concat([away_df, opponent_df])
        except FileNotFoundError:
            continue

    # flip score column names for away dataframe to match home dataframe
    away_df.rename(columns={'Tm': 'Opp', 'Opp': 'Tm'}, inplace=True)

    away_df = away_df.drop(['Location', 'Opp key', 'Rslt', 'Rk', 'Gtm', 'Type'], axis=1)
    away_df.rename(columns=rename_opposing_cols, inplace=True)

    merged_df = pd.merge(home_df, away_df, on=["Date", "Tm", "Opp"])
    merged_df = merged_df.sort_values(by='Date')

    merged_file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}span_full.csv', isWomens)
    merged_df.to_csv(merged_file_path, index=False)

def merge_opponent_data_for_single_season(season, span = 5, isWomens = False):
    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams, unit=f'school ({season} full csv)'):
        try:
            merge_opponent_data_for_school(school_key, season, span, isWomens)
        except FileNotFoundError:
            continue

def merge_opponent_data(seasons, span = 5, isWomens = False):
    for season in seasons:
        merge_opponent_data_for_single_season(season, span, isWomens)

In [76]:
# Step 5: Merge opponent data
for span in [3, 5, 7]:
    for isWomens in [False, True]:
        merge_opponent_data(seasons, span=span, isWomens=isWomens)

100%|██████████| 491/491 [02:57<00:00,  2.76school (2022 full csv)/s]
100%|██████████| 491/491 [03:08<00:00,  2.61school (2023 full csv)/s]
100%|██████████| 491/491 [02:59<00:00,  2.73school (2024 full csv)/s]
100%|██████████| 491/491 [02:52<00:00,  2.84school (2025 full csv)/s]
100%|██████████| 491/491 [01:51<00:00,  4.42school (2026 full csv)/s]
100%|██████████| 370/370 [02:32<00:00,  2.43school (2022 full csv)/s]
100%|██████████| 370/370 [02:42<00:00,  2.27school (2023 full csv)/s]
100%|██████████| 370/370 [02:47<00:00,  2.21school (2024 full csv)/s]
100%|██████████| 370/370 [02:44<00:00,  2.24school (2025 full csv)/s]
100%|██████████| 370/370 [01:47<00:00,  3.44school (2026 full csv)/s]
100%|██████████| 491/491 [02:31<00:00,  3.24school (2022 full csv)/s]
100%|██████████| 491/491 [02:39<00:00,  3.07school (2023 full csv)/s]
100%|██████████| 491/491 [02:38<00:00,  3.10school (2024 full csv)/s]
100%|██████████| 491/491 [02:38<00:00,  3.10school (2025 full csv)/s]
100%|██████████| 491/491 [01:40<00:00,  4.91school (2026 full csv)/s]
100%|██████████| 370/370 [02:19<00:00,  2.64school (2022 full csv)/s]
100%|██████████| 370/370 [02:33<00:00,  2.42school (2023 full csv)/s]
100%|██████████| 370/370 [02:34<00:00,  2.40school (2024 full csv)/s]
100%|██████████| 370/370 [02:32<00:00,  2.43school (2025 full csv)/s]
100%|██████████| 370/370 [01:36<00:00,  3.81school (2026 full csv)/s]
100%|██████████| 491/491 [02:22<00:00,  3.44school (2022 full csv)/s]
100%|██████████| 491/491 [02:29<00:00,  3.28school (2023 full csv)/s]
100%|██████████| 491/491 [02:31<00:00,  3.24school (2024 full csv)/s]
100%|██████████| 491/491 [02:31<00:00,  3.25school (2025 full csv)/s]
100%|██████████| 491/491 [01:31<00:00,  5.40school (2026 full csv)/s]
100%|██████████| 370/370 [02:14<00:00,  2.76school (2022 full csv)/s]
100%|██████████| 370/370 [02:23<00:00,  2.58school (2023 full csv)/s]
100%|██████████| 370/370 [02:25<00:00,  2.54school (2024 full csv)/s]
100%|██████████| 370/370 [02:25<00:00,  2.54school (2025 full csv)/s]
100%|██████████| 370/370 [01:28<00:00,  4.20school (2026 full csv)/s]

Quick visual verification:

In [77]:
school_key, season, span = 'connecticut', 2024, 5
file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}span_full.csv', isWomens=True)
team_df = pd.read_csv(file_path)
team_df.head()

,Rk,Gtm,Date,Location,Opp key,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,def_FG,def_FGA,def_FG%,def_3P,def_3PA,def_3P%,def_2P,def_2PA,def_2P%,def_eFG%,def_FT,def_FTA,def_FT%,def_ORB,def_DRB,def_TRB,def_AST,def_STL,def_BLK,def_TOV,def_PF,ORtg,DRtg,Pace,FTr,3PAr,TS%,TRB%,AST%,STL%,BLK%,TOV%,ORB%,FT/FGA,def_TOV%,def_ORB%,def_FT/FGA,OT_SMA,OT_CMA,OT_EMA,FG_SMA,FG_CMA,FG_EMA,FGA_SMA,FGA_CMA,FGA_EMA,FG%_SMA,FG%_CMA,FG%_EMA,3P_SMA,3P_CMA,3P_EMA,3PA_SMA,3PA_CMA,3PA_EMA,3P%_SMA,3P%_CMA,3P%_EMA,2P_SMA,2P_CMA,2P_EMA,2PA_SMA,2PA_CMA,2PA_EMA,2P%_SMA,2P%_CMA,2P%_EMA,eFG%_SMA,eFG%_CMA,eFG%_EMA,FT_SMA,FT_CMA,FT_EMA,FTA_SMA,FTA_CMA,FTA_EMA,FT%_SMA,FT%_CMA,FT%_EMA,ORB_SMA,ORB_CMA,ORB_EMA,DRB_SMA,DRB_CMA,DRB_EMA,TRB_SMA,TRB_CMA,TRB_EMA,AST_SMA,AST_CMA,AST_EMA,STL_SMA,STL_CMA,STL_EMA,BLK_SMA,BLK_CMA,BLK_EMA,TOV_SMA,TOV_CMA,TOV_EMA,PF_SMA,PF_CMA,PF_EMA,def_FG_SMA,def_FG_CMA,def_FG_EMA,def_FGA_SMA,def_FGA_CMA,def_FGA_EMA,def_FG%_SMA,def_FG%_CMA,def_FG%_EMA,def_3P_SMA,def_3P_CMA,def_3P_EMA,def_3PA_SMA,def_3PA_CMA,def_3PA_EMA,def_3P%_SMA,def_3P%_CMA,def_3P%_EMA,def_2P_SMA,def_2P_CMA,def_2P_EMA,def_2PA_SMA,def_2PA_CMA,def_2PA_EMA,def_2P%_SMA,def_2P%_CMA,def_2P%_EMA,def_eFG%_SMA,def_eFG%_CMA,def_eFG%_EMA,def_FT_SMA,def_FT_CMA,def_FT_EMA,def_FTA_SMA,def_FTA_CMA,def_FTA_EMA,def_FT%_SMA,def_FT%_CMA,def_FT%_EMA,def_ORB_SMA,def_ORB_CMA,def_ORB_EMA,def_DRB_SMA,def_DRB_CMA,def_DRB_EMA,def_TRB_SMA,def_TRB_CMA,def_TRB_EMA,def_AST_SMA,def_AST_CMA,def_AST_EMA,def_STL_SMA,def_STL_CMA,def_STL_EMA,def_BLK_SMA,def_BLK_CMA,def_BLK_EMA,def_TOV_SMA,def_TOV_CMA,def_TOV_EMA,def_PF_SMA,def_PF_CMA,def_PF_EMA,ORtg_SMA,ORtg_CMA,ORtg_EMA,DRtg_SMA,DRtg_CMA,DRtg_EMA,Pace_SMA,Pace_CMA,Pace_EMA,FTr_SMA,FTr_CMA,FTr_EMA,3PAr_SMA,3PAr_CMA,3PAr_EMA,TS%_SMA,TS%_CMA,TS%_EMA,TRB%_SMA,TRB%_CMA,TRB%_EMA,AST%_SMA,AST%_CMA,AST%_EMA,STL%_SMA,STL%_CMA,STL%_EMA,BLK%_SMA,BLK%_CMA,BLK%_EMA,TOV%_SMA,TOV%_CMA,TOV%_EMA,ORB%_SMA,ORB%_CMA,ORB%_EMA,FT/FGA_SMA,FT/FGA_CMA,FT/FGA_EMA,def_TOV%_SMA,def_TOV%_CMA,def_TOV%_EMA,def_ORB%_SMA,def_ORB%_CMA,def_ORB%_EMA,def_FT/FGA_SMA,def_FT/FGA_CMA,def_FT/FGA_EMA,opp_OT,opp_FG,opp_FGA,opp_FG%,opp_3P,opp_3PA,opp_3P%,opp_2P,opp_2PA,opp_2P%,opp_eFG%,opp_FT,opp_FTA,opp_FT%,opp_ORB,opp_DRB,opp_TRB,opp_AST,opp_STL,opp_BLK,opp_TOV,opp_PF,opp_def_FG,opp_def_FGA,opp_def_FG%,opp_def_3P,opp_def_3PA,opp_def_3P%,opp_def_2P,opp_def_2PA,opp_def_2P%,opp_def_eFG%,opp_def_FT,opp_def_FTA,opp_def_FT%,opp_def_ORB,opp_def_DRB,opp_def_TRB,opp_def_AST,opp_def_STL,opp_def_BLK,opp_def_TOV,opp_def_PF,opp_ORtg,opp_DRtg,opp_Pace,opp_FTr,opp_3PAr,opp_TS%,opp_TRB%,opp_AST%,opp_STL%,opp_BLK%,opp_TOV%,opp_ORB%,opp_FT/FGA,opp_def_TOV%,opp_def_ORB%,opp_def_FT/FGA,opp_OT_SMA,opp_OT_CMA,opp_OT_EMA,opp_FG_SMA,opp_FG_CMA,opp_FG_EMA,opp_FGA_SMA,opp_FGA_CMA,opp_FGA_EMA,opp_FG%_SMA,opp_FG%_CMA,opp_FG%_EMA,opp_3P_SMA,opp_3P_CMA,opp_3P_EMA,opp_3PA_SMA,opp_3PA_CMA,opp_3PA_EMA,opp_3P%_SMA,opp_3P%_CMA,opp_3P%_EMA,opp_2P_SMA,opp_2P_CMA,opp_2P_EMA,opp_2PA_SMA,opp_2PA_CMA,opp_2PA_EMA,opp_2P%_SMA,opp_2P%_CMA,opp_2P%_EMA,opp_eFG%_SMA,opp_eFG%_CMA,opp_eFG%_EMA,opp_FT_SMA,opp_FT_CMA,opp_FT_EMA,opp_FTA_SMA,opp_FTA_CMA,opp_FTA_EMA,opp_FT%_SMA,opp_FT%_CMA,opp_FT%_EMA,opp_ORB_SMA,opp_ORB_CMA,opp_ORB_EMA,opp_DRB_SMA,opp_DRB_CMA,opp_DRB_EMA,opp_TRB_SMA,opp_TRB_CMA,opp_TRB_EMA,opp_AST_SMA,opp_AST_CMA,opp_AST_EMA,opp_STL_SMA,opp_STL_CMA,opp_STL_EMA,opp_BLK_SMA,opp_BLK_CMA,opp_BLK_EMA,opp_TOV_SMA,opp_TOV_CMA,opp_TOV_EMA,opp_PF_SMA,opp_PF_CMA,opp_PF_EMA,opp_def_FG_SMA,opp_def_FG_CMA,opp_def_FG_EMA,opp_def_FGA_SMA,opp_def_FGA_CMA,opp_def_FGA_EMA,opp_def_FG%_SMA,opp_def_FG%_CMA,opp_def_FG%_EMA,opp_def_3P_SMA,opp_def_3P_CMA,opp_def_3P_EMA,opp_def_3PA_SMA,opp_def_3PA_CMA,opp_def_3PA_EMA,opp_def_3P%_SMA,opp_def_3P%_CMA,opp_def_3P%_EMA,opp_def_2P_SMA,opp_def_2P_CMA,opp_def_2P_EMA,opp_def_2PA_SMA,opp_def_2PA_CMA,opp_def_2PA_EMA,opp_def_2P%_SMA,opp_def_2P%_CMA,opp_def_2P%_EMA,opp_def_eFG%_SMA,opp_def_eFG%_CMA,opp_def_eFG%_EMA,opp_def_FT_SMA,opp_def_FT_CMA,opp_def_FT_EMA,opp_def_FTA_SMA,opp_def_FTA_CMA,opp_def_FTA_EMA,opp_def_FT%_SMA,opp_def_FT%_CMA,opp_def_FT%_EMA,opp_def_ORB_SMA,opp_def_ORB_CMA,opp_def_ORB_EMA,opp_def_DRB_SMA,opp_def_DRB_CMA,opp_def_DRB_EMA,opp_def_TRB_SMA,opp_def_TRB_CMA,opp_def_TRB_EMA,opp_def_AST_SMA,opp_def_AST_CMA,opp_def_AST_EMA,opp_def_STL_SMA,opp_def_STL_CMA,opp_def_STL_EMA,opp_def_BLK_SMA,opp_def_BLK_CMA,opp_def_BLK_EMA,opp_def_TOV_SMA,opp_def_TOV_CMA,opp_def_TOV_EMA,opp_def_PF_SMA,opp_def_PF_CMA,opp_def_PF_EMA,opp_ORtg_SMA,opp_ORtg_CMA,opp_ORtg_EMA,opp_DRtg_SMA,opp_DRtg_CMA,opp_DRtg_EMA,opp_Pace_SMA,opp_Pace_CMA,opp_Pace_EMA,opp_FTr_SMA,opp_FTr_CMA,opp_FTr_EMA,opp_3PAr_SMA,opp_3PAr_CMA,opp_3PAr_EMA,opp_TS%_SMA,opp_TS%_CMA,opp_TS%_EMA,opp_TRB%_SMA,opp_TRB%_CMA,opp_TRB%_EMA,opp_AST%_SMA,opp_AST%_CMA,opp_AST%_EMA,opp_STL%_SMA,opp_STL%_CMA,opp_STL%_EMA,opp_BLK%_SMA,opp_BLK%_CMA,opp_BLK%_EMA,opp_TOV%_SMA,opp_TOV%_CMA,opp_TOV%_EMA,opp_ORB%_SMA,opp_ORB%_CMA,opp_ORB%_EMA,opp_FT/FGA_SMA,opp_FT/FGA_CMA,opp_FT/FGA_EMA,opp_def_TOV%_SMA,opp_def_TOV%_CMA,opp_def_TOV%_EMA,opp_def_ORB%_SMA,opp_def_ORB%_CMA,opp_def_ORB%_EMA,opp_def_FT/FGA_SMA,opp_def_FT/FGA_CMA,opp_def_FT/FGA_EMA
0,9.0,9.0,2023-12-03,H,connecticut,REG (Non-Conf),W,80.0,68.0,0,31.0,68.0,0.456,5.0,15.0,0.333,26.0,53.0,0.491,0.493,13.0,17.0,0.765,12.0,15.0,27.0,18.0,6.0,2.0,9.0,18.0,26.0,44.0,0.591,4.0,10.0,0.400,22.0,34.0,0.647,0.636,12.0,18.0,0.667,3.0,20.0,23.0,16.0,4.0,2.0,21.0,20.0,111.4,94.7,71.8,0.250,0.221,0.526,54.0,58.1,8.4,5.9,10.6,37.5,0.191,28.6,62.5,0.273,0.0,0.0,0.0,37.2,37.375000,39.057156,67.8,72.000000,70.244170,0.5486,0.519500,0.554334,4.4,4.375000,4.057156,9.6,12.250000,9.959762,0.4518,0.381250,0.417235,32.8,33.000000,35.000000,58.2,59.750000,60.284408,0.5622,0.549750,0.576043,0.5818,0.550625,0.584231,15.0,12.625000,13.336534,21.2,20.125000,19.672611,0.7336,0.633875,0.697290,13.4,16.000000,13.140832,25.4,24.625000,26.778235,38.8,40.625000,39.919067,19.8,21.125000,20.695473,10.8,11.875000,10.777778,5.4,4.750000,5.378144,12.2,11.750000,12.430270,17.2,15.500000,16.940101,19.0,19.500000,20.826246,53.6,52.375000,56.545496,0.3516,0.372625,0.365441,3.6,3.375000,4.101966,12.4,11.875000,13.362140,0.2360,0.244750,0.274097,15.4,16.125000,16.724280,41.2,40.500000,43.183356,0.3742,0.399125,0.390276,0.3844,0.405875,0.400676,7.0,7.500000,8.038866,11.4,12.625000,12.775949,0.6114,0.590250,0.604366,5.4,5.500000,5.876543,15.8,18.000000,16.910837,21.2,23.500000,22.787380,9.4,9.500000,11.303612,4.6,5.625000,5.630087,1.0,1.625000,0.855053,22.2,23.125000,21.101966,20.4,20.250000,18.955190,122.68,119.200000,121.249703,63.14,64.525000,67.708048,76.22,76.650000,78.349520,0.3150,0.286250,0.284620,0.1428,0.170500,0.142861,0.6028,0.564250,0.599796,64.80,63.387500,63.644399,52.62,56.225000,52.194102,14.12,15.550000,13.718564,13.22,11.575000,12.130224,13.48,12.600000,13.435482,45.04,46.350000,42.450572,0.2228,0.182000,0.194101,27.46,28.550000,25.419753,54.96,53.650000,57.549428,0.1266,0.141750,0.136476,0,26,44,0.591,4,10,0.400,22,34,0.647,0.636,12,18,0.667,3,20,23,16,4,2,21,20,31,68,0.456,5,15,0.333,26,53,0.491,0.493,13,17,0.765,12,15,27,18,6,2,9,18,94.7,111.4,71.8,0.409,0.227,0.647,46.0,61.5,5.6,3.8,28.6,16.7,0.273,10.6,83.3,0.191,0.0,0.0,0.0,27.8,29.666667,27.876543,62.8,65.333333,63.378601,0.4440,0.453333,0.439646,5.6,6.333333,5.814815,18.0,19.000000,17.485597,0.2996,0.319167,0.314580,22.2,23.333333,22.061728,44.8,46.333333,45.893004,0.4950,0.502000,0.478074,0.4876,0.500333,0.483844,11.0,11.500000,12.839506,14.8,15.500000,17.263374,0.7390,0.738667,0.739193,8.8,9.666667,10.086420,22.2,23.833333,24.152263,31.0,33.500000,34.238683,14.0,15.500000,14.534979,8.6,9.000000,8.008230,3.2,3.666667,3.049383,12.8,12.000000,12.362140,17.0,16.666667,17.065844,22.2,21.833333,21.674897,59.2,59.333333,58.588477,0.3772,0.369833,0.371926,7.2,7.000000,6.798354,24.0,22.833333,22.152263,0.3066,0.314333,0.308424,15.0,14.833333,14.876543,35.2,36.500000,36.436214,0.4210,0.405167,0.407741,0.4376,0.428500,0.429284,13.4,13.166667,13.139918,17.8,17.666667,17.761317,0.7448,0.738333,0.739712,9.8,9.333333,9.139918,23.4,23.166667,22.827160,33.2,32.500000,31.967078,11.2,10.500000,10.205761,3.6,3.666667,3.629630,1.8,1.833333,1.423868,15.2,16.000000,14.609053,16.0,15.833333,16.543210,98.12,102.733333,101.222634,88.42,85.616667,86.740741,73.44,74.716667,73.174897,0.2388,0.239667,0.276016,0.2832,0.287333,0.270984,0.5182,0.529500,0.518947,48.34,50.500000,51.632510,50.06,51.550000,51.318519,11.56,11.900000,10.800000,9.42,10.183333,8.470782,15.54,14.350000,14.874486,27.84,29.683333,30.985597,0.1778,0.178000,0.205617,17.98,18.766667,17.584774,72.16,70.316667,69.014403,0.2308,0.225667,0.228638
1,8.0,8.0,2023-12-06,H,ball-state,REG (Non-Conf),W,90.0,63.0,0,33.0,56.0,0.589,8.0,21.0,0.381,25.0,35.0,0.714,0.661,16.0,22.0,0.727,5.0,28.0,33.0,17.0,14.0,3.0,17.0,17.0,21.0,56.0,0.375,9.0,25.0,0.360,12.0,31.0,0.387,0.455,12.0,16.0,0.750,1.0,13.0,14.0,13.0,13.0,0.0,17.0,20.0,113.9,79.7,79.0,0.393,0.375,0.677,70.2,51.5,17.7,9.7,20.4,27.8,0.286,21.1,72.2,0.214,0.0,0.0,0.0,26.4,29.142857,27.251029,57.4,62.285714,56.919067,0.4692,0.473000,0.490097,5.0,6.000000,5.209877,15.6,17.714286,14.990398,0.3160,0.330714,0.343053,21.4,23.142857,22.041152,41.8,44.571429,41.928669,0.5182,0.522714,0.534383,0.5120,0.519714,0.534562,11.8,11.571429,12.559671,16.2,15.857143,17.508916,0.7270,0.728429,0.715129,7.8,8.714286,7.724280,23.2,23.285714,22.768176,31.0,32.000000,30.492455,14.2,15.571429,15.023320,8.0,8.285714,6.672154,3.6,3.428571,2.699588,14.6,13.285714,15.241427,16.6,17.142857,18.043896,22.2,23.142857,24.783265,61.0,60.571429,61.725652,0.3634,0.382143,0.399951,6.6,6.714286,6.198903,22.8,21.714286,19.768176,0.2970,0.317000,0.316616,15.6,16.428571,18.584362,38.2,38.857143,41.957476,0.3982,0.417429,0.435494,0.4176,0.437714,0.450523,11.6,13.142857,13.093278,15.6,17.571429,17.507545,0.7406,0.742143,0.748141,10.0,9.714286,10.093278,20.8,22.000000,20.218107,30.8,31.714286,30.311385,11.8,11.571429,12.803841,4.0,4.000000,4.419753,1.0,1.857143,1.615912,14.6,15.000000,12.739369,17.2,16.142857,17.028807,95.96,101.585714,99.048422,86.72,89.300000,94.960494,72.44,74.300000,72.716598,0.2896,0.263857,0.320344,0.2666,0.278714,0.256322,0.5414,0.546286,0.561631,50.12,49.857143,49.755007,53.26,52.971429,54.712346,10.86,11.000000,9.066667,10.18,9.271429,6.913855,18.54,16.385714,19.449657,26.74,27.828571,26.223731,0.2098,0.191571,0.228078,17.26,17.600000,15.256516,73.26,72.171429,73.776269,0.1944,0.220714,0.216092,0,21,56,0.375,9,25,0.360,12,31,0.387,0.455,12,16,0.750,1,13,14,13,13,0,17,20,33,56,0.589,8,21,0.381,25,35,0.714,0.661,16,22,0.727,5,28,33,17,14,3,17,17,79.7,113.9,79.0,0.286,0.446,0.495,29.8,61.9,16.5,0.0,21.1,3.4,0.214,20.4,96.6,0.286,0.0,0.0,0.0,25.8,28.428571,25.834019,60.2,61.285714,60.532236,0.4298,0.465714,0.427930,7.8,8.285714,7.632373,25.2,24.285714,25.262003,0.3182,0.351143,0.310284,18.0,20.142857,18.201646,35.0,37.000000,35.270233,0.5138,0.544286,0.515798,0.4946,0.533286,0.490975,12.0,12.000000,12.698217,17.2,17.857143,17.748971,0.7098,0.678429,0.717859,8.2,7.571429,8.417010,19.2,19.428571,16.831276,27.4,27.000000,25.248285,13.8,16.000000,13.661180,10.6,12.142857,12.646091,2.2,2.000000,1.914952,16.6,15.571429,17.718793,15.6,16.571429,15.805213,25.6,25.857143,27.159122,55.0,55.714286,55.035665,0.4644,0.464857,0.492059,7.0,6.571429,6.368999,17.4,17.000000,15.296296,0.4050,0.389429,0.417733,18.6,19.285714,20.790123,37.6,38.714286,39.739369,0.4944,0.498857,0.522357,0.5278,0.523857,0.549276,9.2,9.142857,8.722908,13.4,13.571429,13.048011,0.7352,0.706714,0.692325,6.6,7.714286,7.552812,23.0,22.428571,23.647462,29.6,30.142857,31.200274,16.6,16.714286,16.677641,6.8,6.428571,7.843621,2.6,2.571429,2.275720,23.2,23.571429,25.395062,18.2,18.571429,18.352538,93.12,99.642857,92.354733,86.88,86.400000,87.928121,77.38,77.914286,78.688477,0.2872,0.295429,0.295239,0.4176,0.396714,0.417071,0.5224,0.553000,0.521827,47.90,47.485714,44.519342,52.32,54.942857,51.687517,13.58,15.528571,16.006036,5.96,5.328571,4.993553,19.36,18.157143,20.300549,26.30,25.400000,25.954321,0.2000,0.199143,0.211416,27.14,27.342857,29.139781,73.70,74.600000,74.045679,0.1694,0.165143,0.159396
2,9.0,9.0,2023-12-10,N,north-carolina,REG (Non-Conf),W,76.0,64.0,0,30.0,65.0,0.462,8.0,17.0,0.471,22.0,48.0,0.458,0.523,8.0,13.0,0.615,8.0,22.0,30.0,20.0,10.0,6.0,14.0,14.0,28.0,68.0,0.412,3.0,10.0,0.300,25.0,58.0,0.431,0.434,5.0,10.0,0.500,15.0,19.0,34.0,14.0,8.0,3.0,19.0,15.0,98.7,83.2,77.0,0.200,0.262,0.534,46.9,66.7,13.0,10.3,16.4,29.6,0.123,20.7,70.4,0.074,0.0,0.0,0.0,26.6,29.625000,29.167353,56.4,61.500000,56.612711,0.4820,0.487500,0.523065,5.4,6.250000,6.139918,16.0,18.125000,16.993599,0.3290,0.337000,0.355702,21.2,23.375000,23.027435,40.4,43.375000,39.619113,0.5372,0.546625,0.594255,0.5294,0.537375,0.576708,13.0,12.125000,13.706447,18.2,16.625000,19.005944,0.7058,0.728250,0.719086,7.2,8.250000,6.816187,23.8,23.875000,24.512117,31.0,32.125000,31.328304,14.0,15.750000,15.682213,7.6,9.000000,9.114769,2.4,3.375000,2.799726,15.0,13.750000,15.827618,17.2,17.125000,17.695930,23.4,22.875000,23.522176,60.6,60.000000,59.817101,0.3866,0.381250,0.391634,7.2,7.000000,7.132602,23.2,22.125000,21.512117,0.3168,0.322375,0.331077,16.2,15.875000,16.389575,37.4,37.875000,38.304984,0.4242,0.413625,0.419329,0.4466,0.439875,0.452015,11.6,13.000000,12.728852,15.4,17.375000,17.005030,0.7494,0.743125,0.748761,8.0,8.625000,7.062186,20.0,20.875000,17.812071,28.0,29.500000,24.874257,12.6,11.750000,12.869227,5.8,5.125000,7.279835,0.8,1.625000,1.077275,12.6,15.250000,14.159579,17.0,16.625000,18.019204,98.20,103.125000,103.998948,90.34,88.100000,89.873663,72.66,74.887500,74.811065,0.3288,0.280000,0.344563,0.2794,0.290750,0.295882,0.5568,0.562625,0.600087,53.34,52.400000,56.570005,52.30,52.787500,53.641564,10.30,11.837500,11.944444,6.98,9.325000,7.842570,18.94,16.887500,19.766438,25.90,27.825000,26.749154,0.2342,0.203375,0.247385,15.68,18.037500,17.204344,74.10,72.175000,73.250846,0.1958,0.219875,0.215395,0,28,68,0.412,3,10,0.300,25,58,0.431,0.434,5,10,0.500,15,19,34,14,8,3,19,15,30,65,0.462,8,17,0.471,22,48,0.458,0.523,8,13,0.615,8,22,30,20,10,6,14,14,83.2,98.7,77.0,0.147,0.147,0.440,53.1,50.0,10.4,6.3,20.7,40.5,0.074,16.4,59.5,0.123,0.0,0.0,0.0,23.6,25.111111,26.029111,59.0,61.888889,61.415333,0.4080,0.409556,0.429067,3.6,5.111111,5.137022,16.0,19.222222,17.747904,0.2518,0.284778,0.307763,20.0,20.000000,20.892090,43.0,42.666667,43.667429,0.4682,0.465667,0.478672,0.4378,0.449889,0.469766,11.8,13.444444,11.484377,18.8,20.222222,16.796373,0.6502,0.675889,0.703761,8.4,10.555556,9.427374,23.8,22.555556,23.955037,32.2,33.111111,33.382411,9.4,12.222222,13.247371,7.6,8.888889,7.380582,4.2,4.444444,4.796373,12.0,11.000000,12.193720,17.0,16.111111,15.686938,21.6,19.333333,21.756287,54.2,52.000000,55.701113,0.4028,0.370667,0.392117,7.2,6.000000,7.011126,18.8,18.666667,17.015546,0.4058,0.320444,0.429363,14.4,13.333333,14.745161,35.4,33.333333,38.685566,0.4314,0.412333,0.401693,0.4704,0.426889,0.455149,11.6,10.888889,11.056546,15.4,14.666667,14.626276,0.7736,0.744444,0.780545,5.8,6.444444,6.984149,25.0,23.666667,23.288371,30.8,30.111111,30.272519,11.4,10.444444,11.137022,5.4,4.777778,6.039323,2.8,2.666667,3.253010,14.8,18.000000,15.099223,20.0,20.111111,18.114312,88.46,96.288889,96.127526,87.60,78.266667,86.424585,71.04,71.244444,71.485155,0.3476,0.350333,0.298793,0.2602,0.297444,0.277851,0.4684,0.483889,0.500098,51.34,52.122222,52.583158,37.64,47.488889,49.091480,10.68,12.400000,10.317162,12.22,13.644444,12.926383,15.22,13.633333,15.183783,25.82,30.288889,28.701189,0.2204,0.232667,0.203778,19.50,23.388889,19.536107,74.18,69.711111,71.298811,0.2236,0.212444,0.206047
3,10.0,10.0,2023-12-16,H,louisville,REG (Non-Conf),W,86.0,62.0,0,32.0,54.0,0.593,7.0,18.0,0.389,25.0,36.0,0.694,0.657,15.0,20.0,0.750,3.0,28.0,31.0,24.0,12.0,7.0,20.0,15.0,25.0,61.0,0.410,4.0,15.0,0.267,21.0,46.0,0.457,0.443,8.0,12.0,0.667,8.0,16.0,24.0,13.0,12.0,3.0,19.0,20.0,108.7,78.4,79.1,0.370,0.333,0.677,56.4,75.0,15.2,15.2,24.0,15.8,0.278,22.2,84.2,0.131,0.0,0.0,0.0,27.4,29.666667,29.444902,57.6,61.888889,59.408474,0.4862,0.484667,0.502710,6.4,6.444444,6.759945,16.4,18.000000,16.995732,0.3832,0.351889,0.394135,21.0,23.222222,22.684957,41.2,43.888889,42.412742,0.5242,0.536778,0.548837,0.5408,0.535778,0.558806,13.2,11.666667,11.804298,18.6,16.222222,17.003963,0.7016,0.715667,0.684391,7.4,8.222222,7.210791,22.6,23.666667,23.674745,30.0,31.888889,30.885536,15.2,16.222222,17.121475,8.0,9.111111,9.409846,2.8,3.666667,3.866484,15.2,13.777778,15.218412,17.4,16.777778,16.463954,25.6,23.444444,25.014784,61.2,60.888889,62.544734,0.4166,0.384667,0.398422,6.6,6.555556,5.755068,18.4,20.777778,17.674745,0.3416,0.319889,0.320718,19.0,16.888889,19.259717,42.8,40.111111,44.869989,0.4394,0.415556,0.423219,0.4718,0.439222,0.446010,11.8,12.111111,10.152568,16.2,16.555556,14.670020,0.7160,0.716111,0.665841,9.4,9.333333,9.708124,19.2,20.666667,18.208048,28.6,30.000000,27.916171,13.8,12.000000,13.246152,6.8,5.444444,7.519890,1.4,1.777778,1.718183,14.2,15.666667,15.773053,18.0,16.444444,17.012803,100.36,102.633333,102.232632,94.50,87.555556,87.649108,73.96,75.122222,75.540710,0.3316,0.271111,0.296375,0.2810,0.287556,0.284588,0.5670,0.559444,0.578058,52.12,51.788889,53.346670,54.88,54.333333,57.994376,10.64,11.966667,12.296296,6.46,9.433333,8.661713,18.86,16.833333,18.644292,27.16,28.022222,27.699436,0.2350,0.194444,0.205924,17.02,18.333333,18.369563,72.84,71.977778,72.300564,0.1982,0.203667,0.168263,0,25,61,0.410,4,15,0.267,21,46,0.457,0.443,8,12,0.667,8,16,24,13,12,3,19,20,32,54,0.593,7,18,0.389,25,36,0.694,0.657,15,20,0.750,3,28,31,24,12,7,20,15,78.4,108.7,79.1,0.197,0.246,0.465,43.6,52.0,15.2,8.3,22.2,22.2,0.131,24.0,77.8,0.278,0.0,0.0,0.0,27.6,27.636364,27.347288,60.0,61.181818,62.871395,0.4604,0.451000,0.436091,5.4,4.818182,4.862623,16.4,16.000000,16.100950,0.3470,0.310182,0.307086,22.2,22.818182,22.484665,43.6,45.181818,46.770445,0.5138,0.507091,0.485147,0.5052,0.490455,0.475076,13.8,18.363636,15.118139,18.6,23.454545,19.799285,0.7674,0.788273,0.772780,13.2,13.727273,15.080391,22.0,23.181818,24.587563,35.2,36.909091,39.667954,14.2,13.818182,12.918949,9.6,10.090909,8.953683,2.2,1.727273,2.096835,14.8,14.454545,14.191705,18.8,18.000000,17.251977,20.4,20.818182,20.427289,49.0,51.545455,52.357026,0.4224,0.410091,0.395371,4.0,5.454545,4.508222,15.8,18.000000,17.625514,0.2256,0.281909,0.238093,16.4,15.363636,15.919067,33.2,33.545455,34.731511,0.5080,0.470909,0.466780,0.4638,0.462909,0.438170,10.6,10.000000,8.456536,17.0,15.181818,14.022625,0.6188,0.645273,0.592153,6.0,6.636364,6.421413,19.6,19.454545,21.087114,25.6,26.090909,27.508527,11.0,10.636364,9.920947,4.8,5.363636,4.844688,2.6,2.090909,2.111653,20.8,20.727273,20.041643,19.8,20.909091,19.373148,104.94,107.454545,103.796586,78.26,78.600000,74.868038,71.16,72.954545,72.016652,0.3416,0.397727,0.333303,0.2662,0.258727,0.254199,0.5446,0.543909,0.519359,56.72,58.181818,58.802379,50.40,49.045455,46.623728,13.56,13.936364,12.480904,6.88,5.218182,6.223121,17.74,16.700000,16.453400,37.88,40.172727,40.604976,0.2502,0.309273,0.251702,26.90,26.372727,25.566621,62.12,59.827273,59.395024,0.2370,0.204818,0.175220

## Generate dataset

In [68]:
# Generate FINAL_FEATURES programmatically from STAT_LABELS
# Each stat gets 3 moving average types (SMA, CMA, EMA) for both team and opponent sides
TEAM_MA_FEATURES = [f'{stat}_{ma}' for stat in STAT_LABELS for ma in ['SMA', 'CMA', 'EMA']]
OPP_MA_FEATURES = [f'opp_{feat}' for feat in TEAM_MA_FEATURES]
FINAL_FEATURES = TEAM_MA_FEATURES + OPP_MA_FEATURES + ['Neutral', 'Win']

print(f'Total features: {len(FINAL_FEATURES)} ({len(TEAM_MA_FEATURES)} team + {len(OPP_MA_FEATURES)} opponent + 2)')

def generate_season_dataset(season, span = 5, isWomens = False):
    all_data_df = pd.DataFrame()

    teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
    for school_key in tqdm(teams):
        file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}span_full.csv', isWomens)

        if os.path.exists(file_path):
            team_df = pd.read_csv(file_path)
            all_data_df = pd.concat([all_data_df, team_df])
        else:
            continue

    # sort by date
    all_data_df = all_data_df.sort_values(by="Date")

    # Add feature for if game is neutral site
    all_data_df['Neutral'] = all_data_df['Location'].apply(lambda x: 1 if x == 'N' else 0)

    # add label for win (1 = win, 0 = loss)
    all_data_df['Win'] = (all_data_df['Tm'] > all_data_df['Opp']).astype(int)

    # remove meta columns
    all_data_df = all_data_df.drop(META_LABELS, axis=1)

    # remove non moving average columns (raw stats for both team and opponent sides)
    all_data_df = all_data_df.drop(STAT_LABELS, axis=1)
    all_data_df = all_data_df.drop([f'opp_{col}' for col in STAT_LABELS], axis=1)

    # Drop any rows with NULL value
    all_data_df.dropna(inplace=True)

    # Drop any duplicate rows
    all_data_df.drop_duplicates(inplace=True)

    # Reorder columns
    all_data_df = all_data_df.reindex(FINAL_FEATURES, axis=1)

    assert all([all_data_df.columns.to_list()[i] == FINAL_FEATURES[i] for i in range(len(FINAL_FEATURES))])

    type = 'women' if isWomens else 'men'
    training_data_path = os.path.abspath(f'../../data/dataset/{type}/{season}_{span}span_dataset.csv')
    all_data_df.to_csv(training_data_path, index=False)

def generate_datasets(seasons, span = 5, isWomens = False):
    for season in seasons:
        generate_season_dataset(season, span, isWomens)

Total features: 356 (177 team + 177 opponent + 2)

In [78]:
# Step 6: Generate season datasets
for span in [3, 5, 7]:
    for isWomens in [False, True]:
        generate_datasets(seasons, span=span, isWomens=isWomens)

100%|██████████| 491/491 [00:15<00:00, 32.24it/s]
100%|██████████| 491/491 [00:14<00:00, 33.58it/s]
100%|██████████| 491/491 [00:15<00:00, 32.33it/s]
100%|██████████| 491/491 [00:15<00:00, 31.91it/s]
100%|██████████| 491/491 [00:13<00:00, 35.98it/s]
100%|██████████| 370/370 [00:14<00:00, 25.91it/s]
100%|██████████| 370/370 [00:14<00:00, 25.78it/s]
100%|██████████| 370/370 [00:14<00:00, 26.32it/s]
100%|██████████| 370/370 [00:14<00:00, 25.78it/s]
100%|██████████| 370/370 [00:13<00:00, 28.22it/s]
100%|██████████| 491/491 [00:15<00:00, 32.42it/s]
100%|██████████| 491/491 [00:15<00:00, 32.62it/s]
100%|██████████| 491/491 [00:15<00:00, 32.45it/s]
100%|██████████| 491/491 [00:14<00:00, 34.00it/s]
100%|██████████| 491/491 [00:14<00:00, 33.87it/s]
100%|██████████| 370/370 [00:13<00:00, 26.62it/s]
100%|██████████| 370/370 [00:13<00:00, 26.64it/s]
100%|██████████| 370/370 [00:13<00:00, 26.44it/s]
100%|██████████| 370/370 [00:14<00:00, 25.32it/s]
100%|██████████| 370/370 [00:13<00:00, 28.20it/s]
100%|██████████| 491/491 [00:14<00:00, 34.35it/s]
100%|██████████| 491/491 [00:14<00:00, 33.31it/s]
100%|██████████| 491/491 [00:15<00:00, 32.64it/s]
100%|██████████| 491/491 [00:14<00:00, 33.61it/s]
100%|██████████| 491/491 [00:13<00:00, 35.72it/s]
100%|██████████| 370/370 [00:13<00:00, 26.65it/s]
100%|██████████| 370/370 [00:14<00:00, 26.14it/s]
100%|██████████| 370/370 [00:13<00:00, 26.85it/s]
100%|██████████| 370/370 [00:13<00:00, 26.97it/s]
100%|██████████| 370/370 [00:13<00:00, 27.93it/s]

In [79]:
isWomens, season, span = False, 2023, 5
type = 'women' if isWomens else 'men'

file_path = os.path.abspath(f'../../data/dataset/{type}/{season}_{span}span_dataset.csv')
team_df = pd.read_csv(file_path)
team_df.head()

,OT_SMA,OT_CMA,OT_EMA,FG_SMA,FG_CMA,FG_EMA,FGA_SMA,FGA_CMA,FGA_EMA,FG%_SMA,FG%_CMA,FG%_EMA,3P_SMA,3P_CMA,3P_EMA,3PA_SMA,3PA_CMA,3PA_EMA,3P%_SMA,3P%_CMA,3P%_EMA,2P_SMA,2P_CMA,2P_EMA,2PA_SMA,2PA_CMA,2PA_EMA,2P%_SMA,2P%_CMA,2P%_EMA,eFG%_SMA,eFG%_CMA,eFG%_EMA,FT_SMA,FT_CMA,FT_EMA,FTA_SMA,FTA_CMA,FTA_EMA,FT%_SMA,FT%_CMA,FT%_EMA,ORB_SMA,ORB_CMA,ORB_EMA,DRB_SMA,DRB_CMA,DRB_EMA,TRB_SMA,TRB_CMA,TRB_EMA,AST_SMA,AST_CMA,AST_EMA,STL_SMA,STL_CMA,STL_EMA,BLK_SMA,BLK_CMA,BLK_EMA,TOV_SMA,TOV_CMA,TOV_EMA,PF_SMA,PF_CMA,PF_EMA,ORtg_SMA,ORtg_CMA,ORtg_EMA,DRtg_SMA,DRtg_CMA,DRtg_EMA,Pace_SMA,Pace_CMA,Pace_EMA,FTr_SMA,FTr_CMA,FTr_EMA,3PAr_SMA,3PAr_CMA,3PAr_EMA,TS%_SMA,TS%_CMA,TS%_EMA,TRB%_SMA,TRB%_CMA,TRB%_EMA,AST%_SMA,AST%_CMA,AST%_EMA,STL%_SMA,STL%_CMA,STL%_EMA,BLK%_SMA,BLK%_CMA,BLK%_EMA,TOV%_SMA,TOV%_CMA,TOV%_EMA,ORB%_SMA,ORB%_CMA,ORB%_EMA,FT/FGA_SMA,FT/FGA_CMA,FT/FGA_EMA,def_FG_SMA,def_FG_CMA,def_FG_EMA,def_FGA_SMA,def_FGA_CMA,def_FGA_EMA,def_FG%_SMA,def_FG%_CMA,def_FG%_EMA,def_3P_SMA,def_3P_CMA,def_3P_EMA,def_3PA_SMA,def_3PA_CMA,def_3PA_EMA,def_3P%_SMA,def_3P%_CMA,def_3P%_EMA,def_2P_SMA,def_2P_CMA,def_2P_EMA,def_2PA_SMA,def_2PA_CMA,def_2PA_EMA,def_2P%_SMA,def_2P%_CMA,def_2P%_EMA,def_eFG%_SMA,def_eFG%_CMA,def_eFG%_EMA,def_FT_SMA,def_FT_CMA,def_FT_EMA,def_FTA_SMA,def_FTA_CMA,def_FTA_EMA,def_FT%_SMA,def_FT%_CMA,def_FT%_EMA,def_ORB_SMA,def_ORB_CMA,def_ORB_EMA,def_DRB_SMA,def_DRB_CMA,def_DRB_EMA,def_TRB_SMA,def_TRB_CMA,def_TRB_EMA,def_AST_SMA,def_AST_CMA,def_AST_EMA,def_STL_SMA,def_STL_CMA,def_STL_EMA,def_BLK_SMA,def_BLK_CMA,def_BLK_EMA,def_TOV_SMA,def_TOV_CMA,def_TOV_EMA,def_PF_SMA,def_PF_CMA,def_PF_EMA,def_TOV%_SMA,def_TOV%_CMA,def_TOV%_EMA,def_ORB%_SMA,def_ORB%_CMA,def_ORB%_EMA,def_FT/FGA_SMA,def_FT/FGA_CMA,def_FT/FGA_EMA,opp_OT_SMA,opp_OT_CMA,opp_OT_EMA,opp_FG_SMA,opp_FG_CMA,opp_FG_EMA,opp_FGA_SMA,opp_FGA_CMA,opp_FGA_EMA,opp_FG%_SMA,opp_FG%_CMA,opp_FG%_EMA,opp_3P_SMA,opp_3P_CMA,opp_3P_EMA,opp_3PA_SMA,opp_3PA_CMA,opp_3PA_EMA,opp_3P%_SMA,opp_3P%_CMA,opp_3P%_EMA,opp_2P_SMA,opp_2P_CMA,opp_2P_EMA,opp_2PA_SMA,opp_2PA_CMA,opp_2PA_EMA,opp_2P%_SMA,opp_2P%_CMA,opp_2P%_EMA,opp_eFG%_SMA,opp_eFG%_CMA,opp_eFG%_EMA,opp_FT_SMA,opp_FT_CMA,opp_FT_EMA,opp_FTA_SMA,opp_FTA_CMA,opp_FTA_EMA,opp_FT%_SMA,opp_FT%_CMA,opp_FT%_EMA,opp_ORB_SMA,opp_ORB_CMA,opp_ORB_EMA,opp_DRB_SMA,opp_DRB_CMA,opp_DRB_EMA,opp_TRB_SMA,opp_TRB_CMA,opp_TRB_EMA,opp_AST_SMA,opp_AST_CMA,opp_AST_EMA,opp_STL_SMA,opp_STL_CMA,opp_STL_EMA,opp_BLK_SMA,opp_BLK_CMA,opp_BLK_EMA,opp_TOV_SMA,opp_TOV_CMA,opp_TOV_EMA,opp_PF_SMA,opp_PF_CMA,opp_PF_EMA,opp_ORtg_SMA,opp_ORtg_CMA,opp_ORtg_EMA,opp_DRtg_SMA,opp_DRtg_CMA,opp_DRtg_EMA,opp_Pace_SMA,opp_Pace_CMA,opp_Pace_EMA,opp_FTr_SMA,opp_FTr_CMA,opp_FTr_EMA,opp_3PAr_SMA,opp_3PAr_CMA,opp_3PAr_EMA,opp_TS%_SMA,opp_TS%_CMA,opp_TS%_EMA,opp_TRB%_SMA,opp_TRB%_CMA,opp_TRB%_EMA,opp_AST%_SMA,opp_AST%_CMA,opp_AST%_EMA,opp_STL%_SMA,opp_STL%_CMA,opp_STL%_EMA,opp_BLK%_SMA,opp_BLK%_CMA,opp_BLK%_EMA,opp_TOV%_SMA,opp_TOV%_CMA,opp_TOV%_EMA,opp_ORB%_SMA,opp_ORB%_CMA,opp_ORB%_EMA,opp_FT/FGA_SMA,opp_FT/FGA_CMA,opp_FT/FGA_EMA,opp_def_FG_SMA,opp_def_FG_CMA,opp_def_FG_EMA,opp_def_FGA_SMA,opp_def_FGA_CMA,opp_def_FGA_EMA,opp_def_FG%_SMA,opp_def_FG%_CMA,opp_def_FG%_EMA,opp_def_3P_SMA,opp_def_3P_CMA,opp_def_3P_EMA,opp_def_3PA_SMA,opp_def_3PA_CMA,opp_def_3PA_EMA,opp_def_3P%_SMA,opp_def_3P%_CMA,opp_def_3P%_EMA,opp_def_2P_SMA,opp_def_2P_CMA,opp_def_2P_EMA,opp_def_2PA_SMA,opp_def_2PA_CMA,opp_def_2PA_EMA,opp_def_2P%_SMA,opp_def_2P%_CMA,opp_def_2P%_EMA,opp_def_eFG%_SMA,opp_def_eFG%_CMA,opp_def_eFG%_EMA,opp_def_FT_SMA,opp_def_FT_CMA,opp_def_FT_EMA,opp_def_FTA_SMA,opp_def_FTA_CMA,opp_def_FTA_EMA,opp_def_FT%_SMA,opp_def_FT%_CMA,opp_def_FT%_EMA,opp_def_ORB_SMA,opp_def_ORB_CMA,opp_def_ORB_EMA,opp_def_DRB_SMA,opp_def_DRB_CMA,opp_def_DRB_EMA,opp_def_TRB_SMA,opp_def_TRB_CMA,opp_def_TRB_EMA,opp_def_AST_SMA,opp_def_AST_CMA,opp_def_AST_EMA,opp_def_STL_SMA,opp_def_STL_CMA,opp_def_STL_EMA,opp_def_BLK_SMA,opp_def_BLK_CMA,opp_def_BLK_EMA,opp_def_TOV_SMA,opp_def_TOV_CMA,opp_def_TOV_EMA,opp_def_PF_SMA,opp_def_PF_CMA,opp_def_PF_EMA,opp_def_TOV%_SMA,opp_def_TOV%_CMA,opp_def_TOV%_EMA,opp_def_ORB%_SMA,opp_def_ORB%_CMA,opp_def_ORB%_EMA,opp_def_FT/FGA_SMA,opp_def_FT/FGA_CMA,opp_def_FT/FGA_EMA,Neutral,Win
0,0.2,0.2,0.148148,30.2,30.2,28.493827,67.6,67.6,65.790123,0.4440,0.4440,0.429864,9.4,9.4,9.382716,30.4,30.4,31.061728,0.3108,0.3108,0.303160,20.8,20.8,19.111111,37.2,37.2,34.728395,0.5572,0.5572,0.547988,0.5138,0.5138,0.501222,15.4,15.4,16.987654,19.4,19.4,20.777778,0.7910,0.7910,0.820469,13.6,13.6,13.518519,23.0,23.0,23.691358,36.6,36.6,37.209877,11.4,11.4,10.925926,8.4,8.4,8.432099,3.4,3.4,3.506173,12.6,12.6,12.234568,22.0,22.0,20.765432,112.06,112.06,111.324691,104.60,104.60,99.338272,74.32,74.32,73.616049,0.2964,0.2964,0.325852,0.4538,0.4538,0.476272,0.5542,0.5542,0.550222,54.42,54.42,54.554321,38.16,38.16,38.697531,11.02,11.02,11.228395,8.90,8.90,8.932099,14.08,14.08,13.898765,37.68,37.68,37.104938,0.2362,0.2362,0.267272,28.4,28.4,27.555556,58.4,58.4,58.382716,0.4858,0.4858,0.471296,6.6,6.6,6.123457,19.8,19.8,18.740741,0.3266,0.3266,0.319926,21.8,21.8,21.432099,38.6,38.6,39.641975,0.5674,0.5674,0.543296,0.5420,0.5420,0.523580,16.6,16.6,13.580247,23.4,23.4,19.888889,0.6692,0.6692,0.626025,8.0,8.0,7.962963,22.6,22.6,22.987654,30.6,30.6,30.950617,14.0,14.0,13.753086,6.4,6.4,6.234568,3.2,3.2,2.271605,15.0,15.0,15.716049,18.0,18.0,18.308642,17.74,17.74,18.806173,62.32,62.32,62.895062,0.2872,0.2872,0.237284,0.0,0.0,0.0,29.6,29.6,28.691358,58.2,58.2,58.098765,0.5074,0.5074,0.492642,9.6,9.6,8.851852,24.0,24.0,23.493827,0.3742,0.3742,0.349630,20.0,20.0,19.839506,34.2,34.2,34.604938,0.5838,0.5838,0.572642,0.5900,0.5900,0.568914,11.8,11.8,11.160494,15.6,15.6,14.975309,0.7638,0.7638,0.745247,6.6,6.6,6.641975,24.8,24.8,24.679012,31.4,31.4,31.320988,15.8,15.8,15.407407,4.6,4.6,5.320988,4.0,4.0,3.925926,7.2,7.2,7.617284,12.4,12.4,12.666667,120.20,120.20,115.797531,94.60,94.60,95.025926,66.96,66.96,66.651852,0.2684,0.2684,0.258111,0.4116,0.4116,0.403827,0.6124,0.6124,0.590790,51.22,51.22,50.518519,53.26,53.26,53.567901,6.92,6.92,8.060494,10.66,10.66,11.138272,9.82,9.82,10.397531,24.06,24.06,23.791358,0.2028,0.2028,0.192111,25.6,25.6,25.419753,62.0,62.0,61.506173,0.4142,0.4142,0.414235,7.4,7.4,7.913580,21.6,21.6,22.716049,0.3342,0.3342,0.339519,18.2,18.2,17.506173,40.4,40.4,38.790123,0.4536,0.4536,0.454593,0.4758,0.4758,0.480802,4.6,4.6,4.493827,7.4,7.4,7.358025,0.5928,0.5928,0.585457,9.0,9.0,9.333333,21.2,21.2,21.716049,30.2,30.2,31.049383,11.6,11.6,11.962963,4.4,4.4,4.716049,2.2,2.2,2.123457,11.2,11.2,11.456790,15.6,15.6,15.012346,14.80,14.80,15.235802,75.94,75.94,76.208642,0.0740,0.0740,0.072025,0,1
1,0.0,0.0,0.000000,28.6,28.6,27.444444,58.2,58.2,58.000000,0.4912,0.4912,0.472457,13.2,13.2,12.728395,29.8,29.8,30.024691,0.4396,0.4396,0.420827,15.4,15.4,14.716049,28.4,28.4,27.975309,0.5520,0.5520,0.534049,0.6042,0.6042,0.581691,6.2,6.2,5.604938,8.4,8.4,7.728395,0.7216,0.7216,0.691235,5.6,5.6,6.123457,26.2,26.2,25.395062,31.8,31.8,31.518519,18.8,18.8,18.037037,5.2,5.2,5.382716,1.8,1.8,1.728395,10.4,10.4,11.037037,14.0,14.0,13.382716,114.34,114.34,109.613580,96.86,96.86,96.807407,66.96,66.96,66.641975,0.1438,0.1438,0.132185,0.5120,0.5120,0.517728,0.6132,0.6132,0.590235,51.68,51.68,50.856790,65.50,65.50,65.434568,7.72,7.72,8.038272,6.40,6.40,6.264198,14.32,14.32,15.191358,19.32,19.32,20.298765,0.1060,0.1060,0.095753,24.8,24.8,24.987654,58.8,58.8,58.691358,0.4252,0.4252,0.428444,7.2,7.2,6.950617,24.0,24.0,24.111111,0.2910,0.2910,0.274938,17.6,17.6,18.037037,34.8,34.8,34.580247,0.5062,0.5062,0.519605,0.4884,0.4884,0.489309,8.0,8.0,7.555556,10.4,10.4,10.086420,0.7284,0.7284,0.706160,6.6,6.6,6.790123,23.6,23.6,24.086420,30.2,30.2,30.876543,13.0,13.0,13.160494,6.6,6.6,7.000000,3.4,3.4,3.728395,9.8,9.8,10.012346,13.0,13.0,12.790123,13.42,13.42,13.693827,80.70,80.70,79.723457,0.1408,0.1408,0.133765,0.0,0.0,0.0,28.0,28.0,28.320988,53.6,53.6,55.197531,0.5220,0.5220,0.513321,7.2,7.2,6.469136,18.4,18.4,17.679012,0.3938,0.3938,0.367975,20.8,20.8,21.851852,35.2,35.2,37.518519,0.5896,0.5896,0.581296,0.5912,0.5912,0.574346,11.0,11.0,9.259259,17.4,17.4,15.370370,0.5970,0.5970,0.565235,4.6,4.6,4.728395,29.2,29.2,28.814815,33.8,33.8,33.543210,17.0,17.0,16.172840,6.0,6.0,5.888889,2.0,2.0,1.679012,11.6,11.6,12.259259,16.2,16.2,16.753086,107.24,107.24,103.362963,89.72,89.72,90.307407,69.36,69.36,70.176543,0.3408,0.3408,0.294716,0.3452,0.3452,0.322272,0.6004,0.6004,0.580148,52.58,52.58,51.001235,61.28,61.28,57.580247,8.64,8.64,8.388889,6.42,6.42,5.330864,15.78,15.78,16.381481,16.80,16.80,16.234568,0.2180,0.2180,0.180370,21.6,21.6,21.382716,57.8,57.8,58.012346,0.3746,0.3746,0.369691,8.2,8.2,7.901235,27.0,27.0,27.604938,0.3068,0.3068,0.290148,13.4,13.4,13.481481,30.8,30.8,30.407407,0.4406,0.4406,0.450383,0.4454,0.4454,0.437840,10.8,10.8,12.740741,14.4,14.4,16.259259,0.7300,0.7300,0.757630,7.8,7.8,8.456790,23.0,23.0,23.987654,30.8,30.8,32.444444,9.4,9.4,9.296296,6.4,6.4,6.456790,2.8,2.8,3.160494,13.0,13.0,13.024691,19.0,19.0,18.246914,16.76,16.76,16.577778,83.20,83.20,83.765432,0.1870,0.1870,0.219370,1,1
2,0.0,0.0,0.000000,28.0,28.0,28.320988,53.6,53.6,55.197531,0.5220,0.5220,0.513321,7.2,7.2,6.469136,18.4,18.4,17.679012,0.3938,0.3938,0.367975,20.8,20.8,21.851852,35.2,35.2,37.518519,0.5896,0.5896,0.581296,0.5912,0.5912,0.574346,11.0,11.0,9.259259,17.4,17.4,15.370370,0.5970,0.5970,0.565235,4.6,4.6,4.728395,29.2,29.2,28.814815,33.8,33.8,33.543210,17.0,17.0,16.172840,6.0,6.0,5.888889,2.0,2.0,1.679012,11.6,11.6,12.259259,16.2,16.2,16.753086,107.24,107.24,103.362963,89.72,89.72,90.307407,69.36,69.36,70.176543,0.3408,0.3408,0.294716,0.3452,0.3452,0.322272,0.6004,0.6004,0.580148,52.58,52.58,51.001235,61.28,61.28,57.580247,8.64,8.64,8.388889,6.42,6.42,5.330864,15.78,15.78,16.381481,16.80,16.80,16.234568,0.2180,0.2180,0.180370,21.6,21.6,21.382716,57.8,57.8,58.012346,0.3746,0.3746,0.369691,8.2,8.2,7.901235,27.0,27.0,27.604938,0.3068,0.3068,0.290148,13.4,13.4,13.481481,30.8,30.8,30.407407,0.4406,0.4406,0.450383,0.4454,0.4454,0.437840,10.8,10.8,12.740741,14.4,14.4,16.259259,0.7300,0.7300,0.757630,7.8,7.8,8.456790,23.0,23.0,23.987654,30.8,30.8,32.444444,9.4,9.4,9.296296,6.4,6.4,6.456790,2.8,2.8,3.160494,13.0,13.0,13.024691,19.0,19.0,18.246914,16.76,16.76,16.577778,83.20,83.20,83.765432,0.1870,0.1870,0.219370,0.0,0.0,0.0,28.6,28.6,27.444444,58.2,58.2,58.000000,0.4912,0.4912,0.472457,13.2,13.2,12.728395,29.8,29.8,30.024691,0.4396,0.4396,0.420827,15.4,15.4,14.716049,28.4,28.4,27.975309,0.5520,0.5520,0.534049,0.6042,0.6042,0.581691,6.2,6.2,5.604938,8.4,8.4,7.728395,0.7216,0.7216,0.691235,5.6,5.6,6.123457,26.2,26.2,25.395062,31.8,31.8,31.518519,18.8,18.8,18.037037,5.2,5.2,5.382716,1.8,1.8,1.728395,10.4,10.4,11.037037,14.0,14.0,13.382716,114.34,114.34,109.613580,96.86,96.86,96.807407,66.96,66.96,66.641975,0.1438,0.1438,0.132185,0.5120,0.5120,0.517728,0.6132,0.6132,0.590235,51.68,51.68,50.856790,65.50,65.50,65.434568,7.72,7.72,8.038272,6.40,6.40,6.264198,14.32,14.32,15.191358,19.32,19.32,20.298765,0.1060,0.1060,0.095753,24.8,24.8,24.987654,58.8,58.8,58.691358,0.4252,0.4252,0.428444,7.2,7.2,6.950617,24.0,24.0,24.111111,0.2910,0.2910,0.274938,17.6,17.6,18.037037,34.8,34.8,34.580247,0.5062,0.5062,0.519605,0.4884,0.4884,0.489309,8.0,8.0,7.555556,10.4,10.4,10.086420,0.7284,0.7284,0.706160,6.6,6.6,6.790123,23.6,23.6,24.086420,30.2,30.2,30.876543,13.0,13.0,13.160494,6.6,6.6,7.000000,3.4,3.4,3.728395,9.8,9.8,10.012346,13.0,13.0,12.790123,13.42,13.42,13.693827,80.70,80.70,79.723457,0.1408,0.1408,0.133765,1,0
3,0.0,0.0,0.000000,25.6,25.6,24.419753,61.0,61.0,59.703704,0.4202,0.4202,0.409012,6.6,6.6,6.234568,22.4,22.4,21.395062,0.2932,0.2932,0.290333,19.0,19.0,18.185185,38.6,38.6,38.308642,0.4922,0.4922,0.474037,0.4742,0.4742,0.461247,10.4,10.4,11.777778,14.0,14.0,15.555556,0.7554,0.7554,0.767259,8.0,8.0,8.691358,18.0,18.0,19.728395,26.0,26.0,28.419753,12.4,12.4,10.901235,7.2,7.2,6.814815,2.4,2.4,2.518519,13.8,13.8,14.567901,16.6,16.6,16.098765,94.74,94.74,93.338272,113.60,113.60,108.376543,72.36,72.36,71.990123,0.2346,0.2346,0.268272,0.3656,0.3656,0.357160,0.5058,0.5058,0.499951,45.22,45.22,48.445679,47.96,47.96,44.496296,9.92,9.92,9.440741,7.84,7.84,8.222222,16.80,16.80,17.751852,24.28,24.28,26.554321,0.1746,0.1746,0.203173,29.6,29.6,28.123457,55.2,55.2,55.012346,0.5360,0.5360,0.511111,9.6,9.6,9.259259,21.6,21.6,21.740741,0.4514,0.4514,0.437284,20.0,20.0,18.864198,33.6,33.6,33.271605,0.5920,0.5920,0.559457,0.6216,0.6216,0.594049,13.6,13.6,12.728395,20.4,20.4,19.728395,0.6506,0.6506,0.637593,6.4,6.4,6.024691,24.8,24.8,24.049383,31.2,31.2,30.074074,13.6,13.6,12.320988,7.4,7.4,7.308642,2.6,2.6,2.308642,12.8,12.8,12.666667,14.2,14.2,14.679012,16.48,16.48,16.458025,75.74,75.74,73.479012,0.2572,0.2572,0.238395,0.0,0.0,0.0,28.0,28.0,27.469136,59.2,59.2,58.098765,0.4734,0.4734,0.472840,7.8,7.8,7.308642,22.8,22.8,21.814815,0.3432,0.3432,0.338938,20.2,20.2,20.160494,36.4,36.4,36.283951,0.5570,0.5570,0.558111,0.5392,0.5392,0.535852,9.4,9.4,10.000000,15.4,15.4,15.444444,0.5938,0.5938,0.635765,7.8,7.8,7.938272,19.0,19.0,19.580247,26.8,26.8,27.518519,13.0,13.0,13.135802,7.8,7.8,8.259259,3.6,3.6,3.777778,12.2,12.2,12.197531,18.8,18.8,19.456790,102.82,102.82,102.766667,108.12,108.12,105.225926,71.18,71.18,70.277778,0.2606,0.2606,0.265975,0.3840,0.3840,0.375074,0.5508,0.5508,0.552259,44.74,44.74,45.672840,46.34,46.34,47.540741,11.12,11.12,11.980247,9.48,9.48,10.317284,15.28,15.28,15.419753,24.82,24.82,25.850617,0.1610,0.1610,0.173593,28.4,28.4,26.962963,57.2,57.2,56.814815,0.4968,0.4968,0.475778,7.0,7.0,7.271605,18.4,18.4,19.456790,0.3776,0.3776,0.373728,21.4,21.4,19.691358,38.8,38.8,37.358025,0.5470,0.5470,0.522556,0.5576,0.5576,0.539173,13.4,13.4,13.074074,20.6,20.6,21.000000,0.6614,0.6614,0.617296,9.2,9.2,9.876543,23.8,23.8,22.827160,33.0,33.0,32.703704,13.2,13.2,12.296296,5.6,5.6,5.148148,3.0,3.0,2.777778,13.6,13.6,13.888889,17.4,17.4,17.333333,16.88,16.88,17.218519,75.18,75.18,74.149383,0.2464,0.2464,0.243383,1,0
4,0.0,0.0,0.000000,24.0,24.0,23.308642,54.2,54.2,54.888889,0.4442,0.4442,0.425728,8.6,8.6,8.530864,22.6,22.6,23.160494,0.3816,0.3816,0.369605,15.4,15.4,14.777778,31.6,31.6,31.728395,0.4900,0.4900,0.467840,0.5238,0.5238,0.503568,8.6,8.6,7.246914,16.0,16.0,14.679012,0.5036,0.5036,0.466136,8.0,8.0,8.543210,25.2,25.2,24.407407,33.2,33.2,32.950617,13.2,13.2,12.320988,4.2,4.2,3.790123,3.4,3.4,3.370370,14.4,14.4,15.024691,16.4,16.4,17.012346,95.64,95.64,92.065432,96.82,96.82,97.885185,68.56,68.56,68.186420,0.2986,0.2986,0.270642,0.4170,0.4170,0.421728,0.5264,0.5264,0.503765,51.74,51.74,51.156790,54.22,54.22,52.380247,6.06,6.06,5.458025,8.10,8.10,8.170370,18.80,18.80,19.455556,27.22,27.22,28.188889,0.1616,0.1616,0.134790,25.4,25.4,25.320988,61.0,61.0,60.444444,0.4206,0.4206,0.423160,5.6,5.6,5.604938,19.4,19.4,19.370370,0.3206,0.3206,0.329235,19.8,19.8,19.716049,41.6,41.6,41.074074,0.4718,0.4718,0.479593,0.4668,0.4668,0.470049,10.0,10.0,10.469136,16.2,16.2,16.703704,0.5974,0.5974,0.612926,10.0,10.0,10.160494,21.4,21.4,21.679012,31.4,31.4,31.839506,10.0,10.0,10.024691,9.0,9.0,9.493827,4.4,4.4,4.740741,10.2,10.2,9.777778,18.4,18.4,18.074074,13.04,13.04,12.590123,72.80,72.80,71.833333,0.1616,0.1616,0.171123,0.0,0.0,0.0,24.6,24.6,24.617284,58.2,58.2,57.851852,0.4182,0.4182,0.420938,5.4,5.4,5.876543,20.0,20.0,20.506173,0.2698,0.2698,0.284025,19.2,19.2,18.740741,38.2,38.2,37.345679,0.4922,0.4922,0.489605,0.4652,0.4652,0.472593,14.4,14.4,13.543210,20.0,20.0,19.679012,0.7066,0.7066,0.678284,6.2,6.2,6.197531,21.4,21.4,22.098765,27.6,27.6,28.296296,10.0,10.0,9.703704,9.6,9.6,8.444444,2.6,2.6,2.012346,17.6,17.6,15.851852,22.0,22.0,21.222222,86.90,86.90,88.662963,102.92,102.92,100.392593,79.64,79.64,77.409877,0.3450,0.3450,0.341074,0.3462,0.3462,0.357914,0.5076,0.5076,0.508469,44.42,44.42,45.288889,41.06,41.06,39.407407,11.70,11.70,10.606173,6.64,6.64,5.144444,20.34,20.34,18.929630,18.86,18.86,18.903704,0.2494,0.2494,0.235210,27.2,27.2,26.049383,57.6,57.6,57.037037,0.4720,0.4720,0.455481,6.2,6.2,6.012346,18.6,18.6,18.506173,0.3382,0.3382,0.328827,21.0,21.0,20.037037,39.0,39.0,38.530864,0.5356,0.5356,0.515864,0.5256,0.5256,0.507963,21.6,21.6,19.876543,29.0,29.0,26.987654,0.7386,0.7386,0.731951,8.0,8.0,7.679012,26.4,26.4,26.395062,34.4,34.4,34.074074,14.4,14.4,13.444444,8.2,8.2,7.283951,3.2,3.2,3.259259,16.8,16.8,15.777778,16.6,16.6,15.777778,18.74,18.74,18.198765,81.16,81.16,81.129630,0.3766,0.3766,0.349395,1,0

## Create full train test split
A typical train-test split for machine learning models is to use 70% of the data for training and 30% for testing.

In [80]:
def generate_test_train(seasons, split_neutral = False, span = 5, isWomens = False):
    type = 'women' if isWomens else 'men'
    data_dir_path = os.path.abspath(f'../../data/dataset/{type}/')
    filenames = [f'{season}_{span}span_dataset.csv' for season in seasons]
    filenames = [f for f in filenames if os.path.exists(os.path.join(data_dir_path, f))]
    merged_df = pd.concat([pd.read_csv(os.path.join(data_dir_path, filename)) for filename in filenames], ignore_index=True)

    print(f'Seasons: {seasons} | Files: {len(filenames)}')
    print(f'Original shape: {merged_df.shape}')
    merged_df.dropna(inplace=True)
    print(f'Shape after dropping rows with null values: {merged_df.shape}')
    merged_df.drop_duplicates(inplace=True)
    print(f'Shape after dropping duplicate rows: {merged_df.shape}')

    if split_neutral:
        # Split the DataFrame into two based on 'Neutral' column
        neutral_df = merged_df[merged_df['Neutral'] == 1]
        home_away_df = merged_df[merged_df['Neutral'] == 0]

        neutral_train_df, neutral_test_df = train_test_split(neutral_df, test_size=0.3)
        home_away_train_df, home_away_test_df = train_test_split(home_away_df, test_size=0.3)

        print(len(neutral_train_df), 'neutral train examples')
        print(len(neutral_test_df), 'neutral test examples')
        print(len(home_away_train_df), 'home/away train examples')
        print(len(home_away_test_df), 'home/away test examples')

        neutral_train_df.to_csv(os.path.join(data_dir_path, f'{span}span_neutral_training_set.csv'), index=False)
        neutral_test_df.to_csv(os.path.join(data_dir_path, f'{span}span_neutral_testing_set.csv'), index=False)
        home_away_train_df.to_csv(os.path.join(data_dir_path, f'{span}span_home_away_training_set.csv'), index=False)
        home_away_test_df.to_csv(os.path.join(data_dir_path, f'{span}span_home_away_testing_set.csv'), index=False)
    else:
        train_df, test_df = train_test_split(merged_df, test_size=0.3)

        print(len(train_df), 'train examples')
        print(len(test_df), 'test examples')

        train_df.to_csv(os.path.join(data_dir_path, f'{span}span_training_set.csv'), index=False)
        test_df.to_csv(os.path.join(data_dir_path, f'{span}span_testing_set.csv'), index=False)

In [81]:
# Step 7: Generate train/test splits
for span in [3, 5, 7]:
    for isWomens in [False, True]:
        generate_test_train(seasons, split_neutral=False, span=span, isWomens=isWomens)

Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (26551, 356)
Shape after dropping rows with null values: (26551, 356)
Shape after dropping duplicate rows: (26551, 356)
18585 train examples
7966 test examples
Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (24549, 356)
Shape after dropping rows with null values: (24549, 356)
Shape after dropping duplicate rows: (24549, 356)
17184 train examples
7365 test examples
Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (23925, 356)
Shape after dropping rows with null values: (23925, 356)
Shape after dropping duplicate rows: (23925, 356)
16747 train examples
7178 test examples
Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (22264, 356)
Shape after dropping rows with null values: (22264, 356)
Shape after dropping duplicate rows: (22264, 356)
15584 train examples
6680 test examples
Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (21638, 356)
Shape after dropping rows with null values: (21638, 356)
Shape after dropping duplicate rows: (21638, 356)
15146 train examples
6492 test examples
Seasons: [2022, 2023, 2024, 2025, 2026] | Files: 5
Original shape: (19997, 356)
Shape after dropping rows with null values: (19997, 356)
Shape after dropping duplicate rows: (19997, 356)
13997 train examples
6000 test examples

In [29]:
isWomens, season, span = False, 2023, 5
type = 'women' if isWomens else 'men'

data_dir_path = os.path.abspath(f'../../data/dataset/{type}/')
file_path = os.path.join(data_dir_path, f'{span}span_training_set.csv')
team_df = pd.read_csv(file_path)
team_df.head()

,OT_SMA,OT_CMA,OT_EMA,FG_SMA,FG_CMA,FG_EMA,FGA_SMA,FGA_CMA,FGA_EMA,FG%_SMA,FG%_CMA,FG%_EMA,3P_SMA,3P_CMA,3P_EMA,3PA_SMA,3PA_CMA,3PA_EMA,3P%_SMA,3P%_CMA,3P%_EMA,2P_SMA,2P_CMA,2P_EMA,2PA_SMA,2PA_CMA,2PA_EMA,2P%_SMA,2P%_CMA,2P%_EMA,eFG%_SMA,eFG%_CMA,eFG%_EMA,FT_SMA,FT_CMA,FT_EMA,FTA_SMA,FTA_CMA,FTA_EMA,FT%_SMA,FT%_CMA,FT%_EMA,ORB_SMA,ORB_CMA,ORB_EMA,DRB_SMA,DRB_CMA,DRB_EMA,TRB_SMA,TRB_CMA,TRB_EMA,AST_SMA,AST_CMA,AST_EMA,STL_SMA,STL_CMA,STL_EMA,BLK_SMA,BLK_CMA,BLK_EMA,TOV_SMA,TOV_CMA,TOV_EMA,PF_SMA,PF_CMA,PF_EMA,ORtg_SMA,ORtg_CMA,ORtg_EMA,DRtg_SMA,DRtg_CMA,DRtg_EMA,Pace_SMA,Pace_CMA,Pace_EMA,FTr_SMA,FTr_CMA,FTr_EMA,3PAr_SMA,3PAr_CMA,3PAr_EMA,TS%_SMA,TS%_CMA,TS%_EMA,TRB%_SMA,TRB%_CMA,TRB%_EMA,AST%_SMA,AST%_CMA,AST%_EMA,STL%_SMA,STL%_CMA,STL%_EMA,BLK%_SMA,BLK%_CMA,BLK%_EMA,TOV%_SMA,TOV%_CMA,TOV%_EMA,ORB%_SMA,ORB%_CMA,ORB%_EMA,FT/FGA_SMA,FT/FGA_CMA,FT/FGA_EMA,opp_OT_SMA,opp_OT_CMA,opp_OT_EMA,opp_FG_SMA,opp_FG_CMA,opp_FG_EMA,opp_FGA_SMA,opp_FGA_CMA,opp_FGA_EMA,opp_FG%_SMA,opp_FG%_CMA,opp_FG%_EMA,opp_3P_SMA,opp_3P_CMA,opp_3P_EMA,opp_3PA_SMA,opp_3PA_CMA,opp_3PA_EMA,opp_3P%_SMA,opp_3P%_CMA,opp_3P%_EMA,opp_2P_SMA,opp_2P_CMA,opp_2P_EMA,opp_2PA_SMA,opp_2PA_CMA,opp_2PA_EMA,opp_2P%_SMA,opp_2P%_CMA,opp_2P%_EMA,opp_eFG%_SMA,opp_eFG%_CMA,opp_eFG%_EMA,opp_FT_SMA,opp_FT_CMA,opp_FT_EMA,opp_FTA_SMA,opp_FTA_CMA,opp_FTA_EMA,opp_FT%_SMA,opp_FT%_CMA,opp_FT%_EMA,opp_ORB_SMA,opp_ORB_CMA,opp_ORB_EMA,opp_DRB_SMA,opp_DRB_CMA,opp_DRB_EMA,opp_TRB_SMA,opp_TRB_CMA,opp_TRB_EMA,opp_AST_SMA,opp_AST_CMA,opp_AST_EMA,opp_STL_SMA,opp_STL_CMA,opp_STL_EMA,opp_BLK_SMA,opp_BLK_CMA,opp_BLK_EMA,opp_TOV_SMA,opp_TOV_CMA,opp_TOV_EMA,opp_PF_SMA,opp_PF_CMA,opp_PF_EMA,opp_ORtg_SMA,opp_ORtg_CMA,opp_ORtg_EMA,opp_DRtg_SMA,opp_DRtg_CMA,opp_DRtg_EMA,opp_Pace_SMA,opp_Pace_CMA,opp_Pace_EMA,opp_FTr_SMA,opp_FTr_CMA,opp_FTr_EMA,opp_3PAr_SMA,opp_3PAr_CMA,opp_3PAr_EMA,opp_TS%_SMA,opp_TS%_CMA,opp_TS%_EMA,opp_TRB%_SMA,opp_TRB%_CMA,opp_TRB%_EMA,opp_AST%_SMA,opp_AST%_CMA,opp_AST%_EMA,opp_STL%_SMA,opp_STL%_CMA,opp_STL%_EMA,opp_BLK%_SMA,opp_BLK%_CMA,opp_BLK%_EMA,opp_TOV%_SMA,opp_TOV%_CMA,opp_TOV%_EMA,opp_ORB%_SMA,opp_ORB%_CMA,opp_ORB%_EMA,opp_FT/FGA_SMA,opp_FT/FGA_CMA,opp_FT/FGA_EMA,Neutral,Win
0,0.0,0.000000,0.000000,32.8,30.761905,33.859198,58.4,59.619048,60.704339,0.5648,0.517143,0.559977,10.6,9.476190,11.066606,24.6,25.380952,26.227220,0.4370,0.373905,0.421551,22.2,21.285714,22.792592,33.8,34.238095,34.477119,0.6560,0.620905,0.661401,0.6558,0.596381,0.651106,9.4,13.285714,10.910131,14.4,17.904762,15.335208,0.6642,0.745905,0.718112,6.2,6.714286,7.437172,25.6,25.714286,25.426523,31.8,32.428571,32.863695,22.4,18.761905,23.840105,7.4,8.142857,8.937835,3.4,2.619048,3.190202,11.4,11.714286,12.193118,12.0,13.857143,11.289761,120.76,115.785714,122.744988,97.34,94.523810,93.777988,71.04,72.785714,73.280726,0.2542,0.306143,0.256825,0.4192,0.421762,0.430965,0.6580,0.620238,0.660992,52.54,50.809524,54.483091,67.74,60.052381,69.892173,10.20,11.123810,12.074912,8.34,7.033333,7.775771,14.82,14.714286,15.070813,23.98,23.047619,28.471487,0.1640,0.225905,0.181188,0.2,0.050000,0.222222,28.0,24.150000,27.345783,54.0,52.700000,54.686316,0.5200,0.462150,0.501527,7.2,6.300000,6.981577,17.6,19.250000,18.201343,0.4078,0.335400,0.385297,20.8,17.850000,20.364206,36.4,33.450000,36.484973,0.5706,0.539700,0.557817,0.5866,0.522550,0.565361,12.6,12.250000,13.460523,18.6,18.600000,20.203173,0.6698,0.648050,0.671764,9.6,8.900000,10.598706,24.6,24.300000,25.338664,34.2,33.200000,35.937370,14.0,12.050000,13.290931,5.4,4.700000,5.954954,4.4,4.550000,4.786303,14.6,15.700000,14.901511,11.2,15.050000,12.390882,110.62,97.445000,108.821535,92.62,92.920000,92.317905,66.94,68.085000,67.303744,0.3438,0.361450,0.370000,0.3246,0.366500,0.331534,0.6036,0.544800,0.585089,59.94,54.180000,59.824362,49.90,49.425000,48.566605,7.76,6.845000,8.507247,13.64,13.935000,14.483823,18.82,20.420000,18.809675,36.72,29.540000,37.739142,0.2318,0.236400,0.245257,0,1
1,0.0,0.214286,0.031119,25.4,26.178571,25.266845,53.6,56.392857,53.239784,0.4742,0.464714,0.475011,6.8,7.571429,7.369742,20.8,20.142857,20.773905,0.3256,0.372107,0.351776,18.6,18.607143,17.897102,32.8,36.250000,32.465879,0.5728,0.516643,0.554521,0.5380,0.531857,0.544906,9.8,12.500000,9.199346,12.8,17.214286,12.414398,0.7632,0.752071,0.726972,6.8,6.785714,5.956910,24.6,23.714286,24.241911,31.4,30.500000,30.198821,9.4,11.035714,9.019282,3.2,3.892857,2.710690,1.6,1.214286,1.347473,10.4,10.750000,10.620666,12.8,15.500000,11.572500,105.20,104.978571,103.751226,112.44,111.371429,116.117837,64.08,66.889286,64.388094,0.2420,0.311143,0.233904,0.3920,0.357393,0.393248,0.5658,0.561357,0.568319,55.82,49.885714,53.960018,37.02,42.525000,35.638959,4.92,5.642857,4.117112,4.68,2.996429,3.601708,14.90,14.242857,15.323369,25.56,21.900000,22.481124,0.1862,0.227929,0.174178,0.0,0.035714,0.003854,27.6,25.250000,28.984290,55.4,54.357143,55.297299,0.4966,0.467143,0.524420,9.0,8.892857,9.379416,22.2,24.857143,21.407601,0.4160,0.357893,0.450341,18.6,16.357143,19.604873,33.2,29.500000,33.889698,0.5576,0.561714,0.578389,0.5778,0.549143,0.609557,11.0,11.892857,10.935153,14.4,16.250000,14.518101,0.7468,0.731393,0.740660,4.4,5.714286,4.524746,22.2,20.857143,23.906737,26.6,26.571429,28.431483,15.2,13.000000,15.990130,6.6,5.892857,6.080742,1.6,2.107143,2.159390,7.8,8.642857,7.821724,14.2,15.857143,13.762600,114.84,109.721429,119.519728,104.54,101.628571,100.404085,65.14,64.567857,65.387182,0.2566,0.300893,0.260239,0.4026,0.455714,0.388400,0.6014,0.576321,0.629526,49.40,47.596429,51.866558,53.66,50.971429,54.011450,10.02,9.014286,9.198223,4.92,6.564286,6.691651,11.18,12.339286,11.199336,16.46,19.732143,17.182780,0.1956,0.219286,0.195447,1,0
2,0.0,0.000000,0.000000,21.4,22.076923,22.600987,54.0,54.846154,54.233796,0.3906,0.406154,0.413907,7.0,6.846154,7.507464,24.0,23.692308,23.062588,0.2810,0.296231,0.322647,14.4,15.230769,15.093523,30.0,31.153846,31.171208,0.4810,0.487077,0.484850,0.4528,0.469154,0.481580,12.0,12.384615,13.472696,16.4,17.230769,17.550326,0.7308,0.707615,0.761264,8.0,7.538462,8.485433,21.6,19.615385,22.352974,29.6,27.153846,30.838407,10.2,9.923077,10.780480,8.6,7.384615,7.885428,3.2,2.692308,3.047187,12.4,11.153846,13.430168,12.8,14.230769,14.163262,91.70,95.069231,96.725515,103.56,109.215385,102.658773,66.68,66.369231,67.753807,0.3100,0.333154,0.331163,0.4452,0.431692,0.427183,0.4942,0.504154,0.523844,48.54,46.030769,52.350473,47.46,44.769231,47.656548,12.76,11.061538,11.538468,7.88,7.130769,7.998130,16.40,14.907692,17.371453,25.86,23.823077,28.835673,0.2274,0.240538,0.253874,0.0,0.000000,0.000000,21.6,25.818182,22.437247,52.4,56.909091,53.880946,0.4140,0.451000,0.416010,6.0,8.090909,6.017054,20.6,22.272727,20.787769,0.2910,0.353455,0.289695,15.6,17.727273,16.420193,31.8,34.636364,33.093177,0.4882,0.507455,0.492652,0.4714,0.521909,0.471636,9.6,10.363636,8.847516,13.6,15.272727,12.746041,0.7120,0.668364,0.700358,8.8,9.181818,8.969754,19.4,20.272727,18.991736,28.2,29.454545,27.961490,9.0,11.818182,9.827973,7.6,6.272727,7.259733,4.0,3.818182,3.466951,11.8,9.909091,11.229724,15.4,17.272727,15.765872,93.20,106.009091,93.828409,101.20,107.863636,103.532631,62.92,65.709091,63.405494,0.2616,0.269455,0.237315,0.3910,0.394091,0.385061,0.5012,0.544091,0.498114,48.36,50.736364,46.331692,41.16,45.409091,43.237051,12.02,9.590909,11.441052,14.00,12.672727,11.307037,16.58,13.536364,15.782111,29.52,31.254545,29.073822,0.1850,0.183182,0.165307,0,1
3,0.0,0.000000,0.000000,21.2,24.566667,20.511025,53.4,60.366667,53.940573,0.3960,0.407867,0.379161,6.0,6.533333,6.179880,20.0,21.600000,20.625035,0.3008,0.297700,0.299291,15.2,18.033333,14.331145,33.4,38.766667,33.315538,0.4488,0.466533,0.420980,0.4522,0.461967,0.436496,9.4,12.700000,9.592454,14.0,18.600000,14.091326,0.6948,0.691400,0.696872,9.2,8.600000,9.208770,24.4,22.700000,23.310784,33.6,31.300000,32.519554,10.8,10.933333,10.751046,5.6,6.166667,5.202331,2.8,3.133333,3.095819,13.0,10.033333,12.112431,12.4,14.933333,11.588317,89.82,96.930000,88.922627,102.78,109.040000,106.451970,64.26,70.463333,63.765633,0.2602,0.312067,0.260630,0.3744,0.359400,0.383060,0.4808,0.494433,0.468247,54.00,46.663333,51.278502,52.40,45.160000,54.935414,8.68,8.730000,8.133618,8.92,8.520000,9.358859,17.92,12.803333,16.773977,29.82,24.576667,28.799290,0.1748,0.213267,0.177389,0.0,0.137931,0.006045,23.8,23.241379,25.132182,56.2,55.310345,57.889451,0.4226,0.420793,0.434513,7.2,7.551724,7.798287,22.2,23.241379,23.953365,0.3218,0.327483,0.327052,16.6,15.689655,17.333895,34.0,32.068966,33.936086,0.4878,0.493207,0.511452,0.4862,0.489621,0.501784,8.2,10.172414,7.294767,12.0,14.206897,10.599271,0.6794,0.725483,0.675730,9.0,7.034483,9.335010,23.2,24.310345,24.523504,32.2,31.344828,33.858515,13.0,12.793103,13.255170,6.0,5.689655,6.385569,4.2,4.000000,4.909406,10.6,10.793103,9.769870,16.6,17.655172,15.604023,98.74,96.758621,103.070530,96.54,99.548276,93.826058,63.86,65.193103,63.275935,0.2238,0.262276,0.188896,0.3916,0.422414,0.412245,0.5100,0.518517,0.520410,49.84,48.900000,51.854268,54.78,55.151724,52.631055,9.40,8.606897,10.042468,13.44,12.013793,16.208105,14.60,14.924138,13.426537,27.98,22.265517,29.339184,0.1530,0.188034,0.130296,1,0
4,0.0,0.047619,0.000507,27.2,27.047619,29.306305,55.6,59.238095,55.664178,0.4912,0.458286,0.529849,9.4,10.000000,9.754063,21.4,25.428571,21.537589,0.4398,0.390286,0.451221,17.8,17.047619,19.552241,34.2,33.809524,34.126589,0.5276,0.502333,0.574127,0.5756,0.543048,0.617301,11.8,9.857143,10.440700,15.4,13.761905,13.434478,0.7680,0.696333,0.773374,7.2,8.190476,7.369591,27.8,25.142857,26.597275,35.0,33.333333,33.966865,16.4,16.142857,16.029085,4.6,6.000000,5.078739,3.0,3.476190,2.214035,11.2,11.333333,11.130897,15.4,15.476190,14.707020,113.94,107.471429,120.474243,97.82,101.723810,100.653150,66.70,68.542857,65.774087,0.2796,0.235952,0.243595,0.3860,0.428667,0.385975,0.6048,0.564571,0.639632,55.88,51.480952,56.301988,61.50,60.423810,55.918108,6.88,8.709524,7.729107,8.16,9.095238,5.976577,15.16,14.695238,15.226808,26.10,25.395238,28.370615,0.2146,0.169571,0.189960,0.0,0.000000,0.000000,23.8,22.894737,24.007009,57.2,56.315789,55.719499,0.4190,0.409105,0.433277,5.0,5.052632,5.536462,13.4,15.315789,14.579926,0.3762,0.318789,0.380586,18.8,17.842105,18.470548,43.8,41.000000,41.139573,0.4298,0.438421,0.444962,0.4634,0.453895,0.483994,12.4,12.105263,14.111591,16.6,17.052632,18.747268,0.7252,0.704737,0.733417,8.4,8.157895,6.640102,24.6,22.000000,26.074284,33.0,30.157895,32.714386,9.4,8.473684,9.836790,5.0,5.789474,4.553171,5.2,4.052632,5.250327,10.2,12.157895,9.612912,16.6,17.473684,16.436402,97.24,92.463158,100.603375,100.54,106.926316,100.897148,66.76,68.021053,67.219955,0.2932,0.304737,0.339719,0.2370,0.273053,0.264810,0.5028,0.490474,0.527599,49.68,47.878947,49.394090,37.84,36.657895,39.805213,7.42,8.494737,6.717143,15.14,11.294737,15.700256,13.60,15.936842,13.048297,23.92,24.952632,20.068518,0.2192,0.215789,0.256305,0,1

# Latest statistic for each team

In [47]:
def generate_latest_stats_dict(season = 2026, spans = [3, 5, 7], isWomens = False):
    download_gamelogs_for_single_season(season, isWomens)
    create_basic_gamelogs_for_single_season(season, isWomens)
    create_advanced_gamelogs_for_single_season(season, isWomens)
    combine_basic_advanced_gamelogs_for_single_season(season, isWomens)

    # Get feature names (without opp_ prefix, Neutral, or Win)
    final_features_no_opp = [feature for feature in FINAL_FEATURES if 'opp_' not in feature and feature not in ['Neutral', 'Win']]

    # Initialize with _meta containing feature names for the API
    latest_stats = {
        "_meta": {
            "features": final_features_no_opp,
            "away_prefix": "opp_",
            "extra_features": ["Neutral"]
        }
    }

    for span in spans:
        latest_stats[span] = {}
        generate_moving_averages_for_single_season(season, keep_latest = True, span = span, isWomens = isWomens)
    
        teams = WOMENS_SR_SCHOOL_KEYS if isWomens else MENS_SR_SCHOOL_KEYS
        for school_key in tqdm(teams):
            file_path = get_team_season_file_path(school_key, season, f'{school_key}_{span}ma.csv', isWomens)

            if os.path.exists(file_path):
                team_df = pd.read_csv(file_path)

                # if team_df has no data, pass
                if team_df.shape[0] < 1:
                    print(f'No data for {school_key} in {season}')
                    continue

                # latest date
                date = team_df.loc[(team_df['Date'] != LATEST) & (team_df['Opp key'] != LATEST)]['Date'].iat[-1]

                # only get latest stats
                team_df = team_df.loc[(team_df['Date'] == LATEST) & (team_df['Opp key'] == LATEST)]

                assert team_df.shape[0] == 1

                # remove meta columns
                team_df = team_df.drop(META_LABELS, axis=1)

                # remove non moving average columns
                team_df = team_df.drop(STAT_LABELS, axis=1)

                # Reorder columns
                team_df = team_df.reindex(final_features_no_opp, axis=1)

                assert len(team_df.columns.to_list()) == len(final_features_no_opp)
                assert all([team_df.columns.to_list()[i] == final_features_no_opp[i] for i in range(len(final_features_no_opp))])

                latest = team_df.iloc[-1:].to_numpy().tolist()
                latest_stats[span][school_key] = {'lastPlayed': date, 'stats': latest[0]}
    
    # Use sport code for filename
    sport = 'ncaaw_basketball' if isWomens else 'ncaam_basketball'
    with open(f'{sport}_team_stats.json', 'w') as json_file:
        json.dump(latest_stats, json_file, indent=2)
        
    return latest_stats

In [31]:
# Generate team stats with _meta embedded
# Output files: ncaam_basketball_team_stats.json, ncaaw_basketball_team_stats.json
# Upload to blob: az storage blob upload --account-name mlmbapi --container-name mlmb-api --name "ncaam_basketball/team-stats" --file ncaam_basketball_team_stats.json --overwrite
# generate_latest_stats_dict(isWomens=False)
# generate_latest_stats_dict(isWomens=True)

# Top 25

In [32]:
# API base URL
# API_BASE_URL = "https://mlmb-func-hbhybddvdmgneyep.eastus-01.azurewebsites.net"
API_BASE_URL = "http://localhost:7071"
BATCH_SIZE = 500  # Max predictions per batch request

def get_ap_top_25(season=2026, is_womens=False):
    """
    Scrape AP Top 25 teams from Sports Reference polls page.
    
    Args:
        season: The season year (e.g., 2026)
        is_womens: Whether to get women's rankings
        
    Returns:
        List of team keys (SR school keys)
    """
    gender = 'women' if is_womens else 'men'
    url = f'https://www.sports-reference.com/cbb/seasons/{gender}/{season}-polls.html'
    
    print(f"Fetching AP Top 25 from: {url}")
    
    response = requests.get(url, headers=SCRAPE_HEADERS)
    
    if response.status_code == 429:
        print("Rate limited! Waiting 10 seconds...")
        time.sleep(10)
        response = requests.get(url, headers=SCRAPE_HEADERS)
    
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        return []
    
    soup = BeautifulSoup(response.content, 'html.parser')
    teams = []
    
    # Look for the current-poll table
    for table in soup.find_all('table'):
        table_id = table.get('id', '')
        if 'current-poll' in table_id.lower() or 'ap' in table_id.lower():
            for link in table.find_all('a'):
                href = link.get('href', '')
                match = re.search(r'/cbb/schools/([^/]+)/', href)
                if match:
                    school_key = match.group(1)
                    if school_key not in teams:
                        teams.append(school_key)
                    if len(teams) >= 25:
                        break
            if teams:
                break
    
    print(f"Found {len(teams)} teams")
    return teams[:25]


def generate_top25(sport="ncaam_basketball", spans=[3, 5, 7], season=2026):
    """
    Generate top 25 rankings by running predictions for all matchups.
    Uses batch API for efficient processing. Chunks requests into batches of 500.
    """
    is_womens = sport == "ncaaw_basketball"
    
    # Fetch current AP Top 25
    top_25_teams = get_ap_top_25(season=season, is_womens=is_womens)
    
    if len(top_25_teams) < 25:
        print(f"Warning: Only found {len(top_25_teams)} teams")
    
    # Build all prediction requests
    top_25_matchups = list(permutations(top_25_teams, 2))
    
    batch_requests = []
    for team1, team2 in top_25_matchups:
        for span in spans:
            for neutral in [True, False]:
                batch_requests.append({
                    "home_team": team1,
                    "away_team": team2,
                    "sport": sport,
                    "span": span,
                    "neutral": neutral
                })
    
    total_predictions = len(batch_requests)
    num_batches = (total_predictions + BATCH_SIZE - 1) // BATCH_SIZE
    print(f"Sending {total_predictions} predictions in {num_batches} batches...")
    
    # Send batch requests in chunks
    all_predictions = []
    start_time = time.time()
    
    for i in tqdm(range(0, total_predictions, BATCH_SIZE), desc="Batches"):
        chunk = batch_requests[i:i + BATCH_SIZE]
        response = requests.post(f"{API_BASE_URL}/predictions/batch", json={"input": chunk})
        
        if response.status_code != 200:
            print(f"Batch {i // BATCH_SIZE + 1} failed: {response.status_code}")
            print(response.text)
            continue
        
        result = response.json()
        all_predictions.extend(result.get("output", []))
    
    elapsed = time.time() - start_time
    print(f"Complete in {elapsed:.1f} seconds ({len(all_predictions)} predictions)")
    
    # Aggregate scores
    scores = {}
    for pred in all_predictions:
        if pred.get('type') == 'error':
            error = pred.get('error', {})
            print(f"Prediction error: {error.get('message', 'Unknown error')}")
            continue
            
        home_team = pred['home_team']
        away_team = pred['away_team']
        home_prob = pred.get('home_win_probability', 0.5)
        away_prob = 1 - home_prob
        
        scores[home_team] = scores.get(home_team, 0) + round(home_prob, 4)
        scores[away_team] = scores.get(away_team, 0) + round(away_prob, 4)
    
    # Sort by score descending
    sorted_scores = dict(sorted(scores.items(), key=lambda x: x[1], reverse=True))
    
    with open(f'{sport}_top25.json', 'w') as json_file:
        json.dump(sorted_scores, json_file, indent=2)
    
    return sorted_scores

# Generate rankings
# Output files: ncaam_basketball_top25.json, ncaaw_basketball_top25.json
# Upload to blob: az storage blob upload --account-name mlmbapi --container-name mlmb-api --name "ncaam_basketball/top25" --file ncaam_basketball_top25.json --overwrite
# generate_top25(sport="ncaam_basketball")
# generate_top25(sport="ncaaw_basketball")